# Análisis de Elecciones Presidenciales 2002 de Ecuador

Descripción

Campos de la base resultante:
La base que necesitamos construir deberá tener las siguientes columnas:
- Año
- Vuelta
- Parroquia
- Cantón
- Provincia
- Electores
- Sufragantes
- Votos nulos
- Votos blancos
- Votos inválidos
- Votos válidos
- Candidato
- Organización política
- Votos femeninos por el candidato
- Votos masculinos por el candidato
- Votos totales por el candidato
- Estado del candidato (ganó o no ganó)

### Librerias

In [7]:
# Se instalan las librerías necesarias

# Para leer archivos.sav
! pip install pyreadstat           
 # Para trabajar con dataframes
! pip install pandas              
# Para trabajar con matrices
! pip install numpy                
# Para hacer un reporte de los datos
! pip install pandas-profiling

Requirement already satisfied: pyreadstat in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (1.2.2)
Requirement already satisfied: pandas>=1.2.0 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from pyreadstat) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\saidm\appdata\roaming\python\python310\site-packages (from pandas>=1.2.0->pyreadstat) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from pandas>=1.2.0->pyreadstat) (2023.2)
Requirement already satisfied: numpy>=1.21.0 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from pandas>=1.2.0->pyreadstat) (1.23.5)
Requirement already satisfied: six>=1.5 in c:\users\saidm\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.1->pandas>=1.2.0->pyreadstat) (1.16.0)
Requirement already satisfied: pandas in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\saidm\appdata\roaming\python\python310\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2023.2)
Requirement already satisfied: numpy>=1.21.0 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in c:\users\saidm\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Requirement already satisfied: numpy in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (1.23.5)
Requirement already satisfied: pandas-profiling in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (3.6.6)
Requirement already satisfied: ydata-profiling in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from pandas-profiling) (4.3.1)
Requirement already satisfied: scipy<1.11,>=1.4.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (1.10.1)
Requirement already satisfied: pandas!=1.4.0,<2.1,>1.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (1.5.3)
Requirement already satisfied: matplotlib<4,>=3.2 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (3.7.1)
Requirement already satisfied: pydantic<2,>=1.8.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (1.10.10)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (6.0)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (3.1.2)
Requirement already satisfied: visions[type_image_path]==0.7.5 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (0.7.5)
Requirement already satisfied: numpy<1.24,>=1.16.0 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (1.23.5)
Requirement already satisfied: htmlmin==0.1.12 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (0.1.12)
Requirement already satisfied: phik<0.13,>=0.11.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (0.12.3)
Requirement already satisfied: requests<3,>=2.24.0 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (2.31.0)
Requirement already satisfied: tqdm<5,>=4.48.2 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (4.65.0)
Requirement already satisfied: seaborn<0.13,>=0.10.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (0.12.2)
Requirement already satisfied: multimethod<2,>=1.4 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (1.9.1)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (0.14.0)
Requirement already satisfied: typeguard<3,>=2.13.2 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (2.13.3)
Requirement already satisfied: imagehash==4.3.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (4.3.1)
Requirement already satisfied: wordcloud>=1.9.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (1.9.2)
Requirement already satisfied: dacite>=1.8 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (1.8.1)
Requirement already satisfied: PyWavelets in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from imagehash==4.3.1->ydata-profiling->pandas-profiling) (1.4.1)
Requirement already satisfied: pillow in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from imagehash==4.3.1->ydata-profiling->pandas-profiling) (9.4.0)
Requirement already satisfied: attrs>=19.3.0 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from visions[type_image_path]==0.7.5->ydata-profiling->pandas-profiling) (23.1.0)
Requirement already satisfied: networkx>=2.4 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from visions[type_image_path]==0.7.5->ydata-profiling->pandas-profiling) (3.0)
Requirement already satisfied: tangled-up-in-unicode>=0.0.4 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from visions[type_image_path]==0.7.5->ydata-profiling->pandas-profiling) (0.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling->pandas-profiling) (2.1.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (1.0.7)
Requirement already satisfied: cycler>=0.10 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (4.39.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\saidm\appdata\roaming\python\python310\site-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (23.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\saidm\appdata\roaming\python\python310\site-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from pandas!=1.4.0,<2.1,>1.1->ydata-profiling->pandas-profiling) (2023.2)
Requirement already satisfied: joblib>=0.14.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from phik<0.13,>=0.11.1->ydata-profiling->pandas-profiling) (1.3.1)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from pydantic<2,>=1.8.1->ydata-profiling->pandas-profiling) (4.7.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (2.0.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (2023.5.7)
Requirement already satisfied: patsy>=0.5.2 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling->pandas-profiling) (0.5.3)
Requirement already satisfied: colorama in c:\users\saidm\appdata\roaming\python\python310\site-packages (from tqdm<5,>=4.48.2->ydata-profiling->pandas-profiling) (0.4.6)
Requirement already satisfied: six in c:\users\saidm\appdata\roaming\python\python310\site-packages (from patsy>=0.5.2->statsmodels<1,>=0.13.2->ydata-profiling->pandas-profiling) (1.16.0)

In [8]:
# Se importan las librerías necesarias

import pandas as pd
import numpy as np
import pyreadstat as py
from pandas_profiling import ProfileReport
import matplotlib.pyplot as plt

### Limpieza y Preparación de Datos de la Base de Datos de la Segunda Vuelta
La base es"resultados_presidenciales_2002.csv"

In [9]:
provincias = pd.read_csv("../raw//diccionarios/provincias_2002.csv",sep=',')

In [10]:
provincias.drop(columns=['Unnamed: 0'],inplace=True)

In [11]:
provincias

    PROVINCIA_CODIGO  PROVINCIA_NOMBRE
0                1.0             AZUAY
1                2.0           BOLIVAR
2                3.0             CANAR
3                4.0            CARCHI
4                5.0          COTOPAXI
5                6.0        CHIMBORAZO
6                7.0            EL ORO
7                8.0        ESMERALDAS
8                9.0            GUAYAS
9               10.0          IMBABURA
10              11.0              LOJA
11              12.0          LOS RIOS
12              13.0            MANABI
13              14.0   MORONA SANTIAGO
14              15.0              NAPO
15              16.0           PASTAZA
16              17.0         PICHINCHA
17              18.0        TUNGURAHUA
18              19.0  ZAMORA CHINCHIPE
19              20.0         GALAPAGOS
20              21.0         SUCUMBIOS
21              22.0          ORELLANA

In [12]:
cne2002resultadosV2, meta = py.read_sav("../raw/resultados/resultados a nivel parroquial - segunda vuelta.sav")

In [13]:
cne2002resultadosV2

,DIGNIDAD_CODIGO,PROVINCIA_CODIGO,CANTON_CODIGO,PARROQUIA_CODIGO,SEXO,NUMERO_DE_JUNTAS,VOTOS_EN_BLANCO,VOTOS_NULOS,OP_CODIGO,CANDIDATO_CODIGO,CANDIDATO_VOTOS,CANDIDATO_ESTADO
0,1.0,1.0,260.0,285.0,1.0,30.0,25.0,321.0,202.0,1.000000e+12,2424.0,1.0
1,1.0,1.0,260.0,285.0,1.0,30.0,25.0,321.0,7.0,1.000000e+12,494.0,NaN
2,1.0,1.0,260.0,285.0,2.0,31.0,54.0,373.0,202.0,1.000000e+12,3099.0,1.0
3,1.0,1.0,260.0,285.0,2.0,31.0,54.0,373.0,7.0,1.000000e+12,660.0,NaN
4,1.0,1.0,260.0,730.0,1.0,11.0,11.0,81.0,202.0,1.000000e+12,873.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
4639,1.0,22.0,935.0,3480.0,2.0,1.0,1.0,9.0,7.0,1.000000e+12,10.0,NaN
4640,1.0,22.0,935.0,6455.0,1.0,7.0,3.0,97.0,202.0,1.000000e+12,1171.0,1.0
4641,1.0,22.0,935.0,6455.0,1.0,7.0,3.0,97.0,7.0,1.000000e+12,229.0,NaN
4642,1.0,22.0,935.0,6455.0,2.0,6.0,9.0,149.0,202.0,1.000000e+12,809.0,1.0
4643,1.0,22.0,935.0,6455.0,2.0,6.0,9.0,149.0,7.0,1.000000e+12,222.0,NaN

In [14]:
cne2002resultadosV2.dtypes

DIGNIDAD_CODIGO     float64
PROVINCIA_CODIGO    float64
CANTON_CODIGO       float64
PARROQUIA_CODIGO    float64
SEXO                float64
NUMERO_DE_JUNTAS    float64
VOTOS_EN_BLANCO     float64
VOTOS_NULOS         float64
OP_CODIGO           float64
CANDIDATO_CODIGO    float64
CANDIDATO_VOTOS     float64
CANDIDATO_ESTADO    float64
dtype: object

In [15]:
# Cargar el diccionario 'provincias_2002.csv' en un DataFrame
diccionario_csv = pd.read_csv("../raw//diccionarios/provincias_2002.csv",sep=',')
diccionario_csv.drop(columns=['Unnamed: 0'],inplace=True)
# Convertir el tipo de datos de la columna 'PROVINCIA_CODIGO' a string en el DataFrame 'cne2002resultadosV2'
cne2002resultadosV2['PROVINCIA_CODIGO'] = cne2002resultadosV2['PROVINCIA_CODIGO'].astype(str)

# Limpiar las claves del diccionario 'mapeo_csv' y los valores de la columna 'PROVINCIA_CODIGO'
mapeo_csv = dict(zip(diccionario_csv['PROVINCIA_CODIGO'].astype(str), diccionario_csv['PROVINCIA_NOMBRE']))
# Mapear los códigos de provincia del DataFrame 'cne2002resultadosV2' utilizando el diccionario CSV
cne2002resultadosV2['PROVINCIA_CODIGO'] = cne2002resultadosV2['PROVINCIA_CODIGO'].map(mapeo_csv)


#capitalizar todas las palabras de la columna 'PROVINCIA_CODIGO'
cne2002resultadosV2['PROVINCIA_CODIGO'] = cne2002resultadosV2['PROVINCIA_CODIGO'].str.title()
# Cargar el diccionario estandarizado 'provincias.tsv' en un DataFrame
diccionario_estandarizado = pd.read_csv('../diccionarios estandar/provincias.tsv', sep='\t')
# Crear un diccionario de mapeo de código a nombre de provincia del diccionario estandarizado
mapeo_estandarizado = dict(zip(diccionario_estandarizado['provincia'], diccionario_estandarizado['cod_provincia']))

# Mapear los códigos de provincia del DataFrame 'cne2002resultadosV2' utilizando el diccionario estandarizado
cne2002resultadosV2['PROVINCIA_CODIGO'] = cne2002resultadosV2['PROVINCIA_CODIGO'].map(mapeo_estandarizado)

In [16]:
# Imprimir el DataFrame actualizado
cne2002resultadosV2

,DIGNIDAD_CODIGO,PROVINCIA_CODIGO,CANTON_CODIGO,PARROQUIA_CODIGO,SEXO,NUMERO_DE_JUNTAS,VOTOS_EN_BLANCO,VOTOS_NULOS,OP_CODIGO,CANDIDATO_CODIGO,CANDIDATO_VOTOS,CANDIDATO_ESTADO
0,1.0,P1,260.0,285.0,1.0,30.0,25.0,321.0,202.0,1.000000e+12,2424.0,1.0
1,1.0,P1,260.0,285.0,1.0,30.0,25.0,321.0,7.0,1.000000e+12,494.0,NaN
2,1.0,P1,260.0,285.0,2.0,31.0,54.0,373.0,202.0,1.000000e+12,3099.0,1.0
3,1.0,P1,260.0,285.0,2.0,31.0,54.0,373.0,7.0,1.000000e+12,660.0,NaN
4,1.0,P1,260.0,730.0,1.0,11.0,11.0,81.0,202.0,1.000000e+12,873.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
4639,1.0,P22,935.0,3480.0,2.0,1.0,1.0,9.0,7.0,1.000000e+12,10.0,NaN
4640,1.0,P22,935.0,6455.0,1.0,7.0,3.0,97.0,202.0,1.000000e+12,1171.0,1.0
4641,1.0,P22,935.0,6455.0,1.0,7.0,3.0,97.0,7.0,1.000000e+12,229.0,NaN
4642,1.0,P22,935.0,6455.0,2.0,6.0,9.0,149.0,202.0,1.000000e+12,809.0,1.0
4643,1.0,P22,935.0,6455.0,2.0,6.0,9.0,149.0,7.0,1.000000e+12,222.0,NaN

In [17]:
#Formatear las columnas necesarios como tipo int
cne2002resultadosV2["DIGNIDAD_CODIGO"] = cne2002resultadosV2["DIGNIDAD_CODIGO"].astype(int)
cne2002resultadosV2["SEXO"] = cne2002resultadosV2["SEXO"].astype(int)
cne2002resultadosV2["NUMERO_DE_JUNTAS"] = cne2002resultadosV2["NUMERO_DE_JUNTAS"].astype(int)
cne2002resultadosV2["VOTOS_EN_BLANCO"] = cne2002resultadosV2["VOTOS_EN_BLANCO"].astype(int)
cne2002resultadosV2["VOTOS_NULOS"] = cne2002resultadosV2["VOTOS_NULOS"].astype(int)
cne2002resultadosV2["CANDIDATO_VOTOS"] = cne2002resultadosV2["CANDIDATO_VOTOS"].astype(int)

In [18]:
cne2002resultadosV2

,DIGNIDAD_CODIGO,PROVINCIA_CODIGO,CANTON_CODIGO,PARROQUIA_CODIGO,SEXO,NUMERO_DE_JUNTAS,VOTOS_EN_BLANCO,VOTOS_NULOS,OP_CODIGO,CANDIDATO_CODIGO,CANDIDATO_VOTOS,CANDIDATO_ESTADO
0,1,P1,260.0,285.0,1,30,25,321,202.0,1.000000e+12,2424,1.0
1,1,P1,260.0,285.0,1,30,25,321,7.0,1.000000e+12,494,NaN
2,1,P1,260.0,285.0,2,31,54,373,202.0,1.000000e+12,3099,1.0
3,1,P1,260.0,285.0,2,31,54,373,7.0,1.000000e+12,660,NaN
4,1,P1,260.0,730.0,1,11,11,81,202.0,1.000000e+12,873,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
4639,1,P22,935.0,3480.0,2,1,1,9,7.0,1.000000e+12,10,NaN
4640,1,P22,935.0,6455.0,1,7,3,97,202.0,1.000000e+12,1171,1.0
4641,1,P22,935.0,6455.0,1,7,3,97,7.0,1.000000e+12,229,NaN
4642,1,P22,935.0,6455.0,2,6,9,149,202.0,1.000000e+12,809,1.0
4643,1,P22,935.0,6455.0,2,6,9,149,7.0,1.000000e+12,222,NaN

In [19]:
#Esta forma de agrupar produce que hayan 4 entradas por cada provincia. Son por los dos sexos y los dos candidatos

# si se retira "PROVINCIA_CODIGO" del groupby, se obtiene el resultado a nivel nacional
cne2002agV2 = cne2002resultadosV2.groupby(['CANDIDATO_CODIGO', 'SEXO','PROVINCIA_CODIGO']).agg({
    'NUMERO_DE_JUNTAS': 'sum',
    'VOTOS_EN_BLANCO': 'sum',
    'VOTOS_NULOS': 'sum',
    'CANDIDATO_VOTOS': 'sum'
}).reset_index()
# Crear una columna que muestre la descripción del SEXO
cne2002agV2['SEXO_DESCRIPCION'] = cne2002agV2['SEXO'].map({1: 'MASCULINO', 2: 'FEMENINO'})
cne2002agV2.drop(columns=['SEXO'],inplace=True)

In [20]:
# Mostrar el DataFrame resultante
cne2002agV2

,CANDIDATO_CODIGO,PROVINCIA_CODIGO,NUMERO_DE_JUNTAS,VOTOS_EN_BLANCO,VOTOS_NULOS,CANDIDATO_VOTOS,SEXO_DESCRIPCION
0,1.000000e+12,P1,1048,993,14264,83266,MASCULINO
1,1.000000e+12,P10,411,744,10403,47738,MASCULINO
2,1.000000e+12,P11,510,671,6584,52028,MASCULINO
3,1.000000e+12,P12,1139,1577,13852,76836,MASCULINO
4,1.000000e+12,P13,2253,2846,24175,105432,MASCULINO
...,...,...,...,...,...,...,...
83,1.000000e+12,P5,432,1229,13734,16877,FEMENINO
84,1.000000e+12,P6,538,1921,19549,19639,FEMENINO
85,1.000000e+12,P7,618,871,11319,42739,FEMENINO
86,1.000000e+12,P8,433,835,9781,43571,FEMENINO
87,1.000000e+12,P9,5408,6878,82159,495478,FEMENINO

In [21]:
# Mostrar el DataFrame resultante
cne2002agV2

,CANDIDATO_CODIGO,PROVINCIA_CODIGO,NUMERO_DE_JUNTAS,VOTOS_EN_BLANCO,VOTOS_NULOS,CANDIDATO_VOTOS,SEXO_DESCRIPCION
0,1.000000e+12,P1,1048,993,14264,83266,MASCULINO
1,1.000000e+12,P10,411,744,10403,47738,MASCULINO
2,1.000000e+12,P11,510,671,6584,52028,MASCULINO
3,1.000000e+12,P12,1139,1577,13852,76836,MASCULINO
4,1.000000e+12,P13,2253,2846,24175,105432,MASCULINO
...,...,...,...,...,...,...,...
83,1.000000e+12,P5,432,1229,13734,16877,FEMENINO
84,1.000000e+12,P6,538,1921,19549,19639,FEMENINO
85,1.000000e+12,P7,618,871,11319,42739,FEMENINO
86,1.000000e+12,P8,433,835,9781,43571,FEMENINO
87,1.000000e+12,P9,5408,6878,82159,495478,FEMENINO

### Limpieza y Preparación de Datos de la Base de Datos de la Primera Vuelta
La base es "RESULTADOS_1V_PARROQUIA_2002 (1).SAV"

In [22]:
cne2002resultadosV1, meta = py.read_sav("../raw/resultados/RESULTADOS_1V_PARROQUIA_2002.SAV")

In [23]:
cne2002resultadosV1

,DIGNIDAD_CODIGO,PROVINCIA_CODIGO,CANTON_CODIGO,PARROQUIA_CODIGO,SEXO,NUMERO_DE_ACTAS,VOTOS_EN_BLANCO,VOTOS_NULOS,OP_CODIGO,OP_VOTOS_EN_PLANCHA,CANDIDATO_CODIGO,CANDIDATO_VOTOS,CANDIDATO_ESTADO
0,1.0,1.0,260.0,285.0,2.0,31.0,204.0,381.0,201.0,0.0,1.000000e+12,59.0,NaN
1,1.0,1.0,260.0,285.0,2.0,31.0,204.0,381.0,202.0,0.0,1.000000e+12,637.0,1.0
2,1.0,1.0,260.0,285.0,2.0,31.0,204.0,381.0,6.0,0.0,1.000000e+12,111.0,NaN
3,1.0,1.0,260.0,285.0,2.0,31.0,204.0,381.0,7.0,0.0,1.000000e+12,337.0,NaN
4,1.0,1.0,260.0,285.0,2.0,31.0,204.0,381.0,10.0,0.0,1.000000e+12,142.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
642941,8.0,22.0,935.0,6455.0,1.0,7.0,278.0,230.0,28.0,34.0,8.000000e+12,0.0,NaN
642942,8.0,22.0,935.0,6455.0,1.0,7.0,278.0,230.0,28.0,34.0,8.000000e+12,0.0,NaN
642943,8.0,22.0,935.0,6455.0,1.0,7.0,278.0,230.0,28.0,34.0,8.000000e+12,0.0,NaN
642944,8.0,22.0,935.0,6455.0,1.0,7.0,278.0,230.0,28.0,34.0,8.000000e+12,0.0,NaN
642945,8.0,22.0,935.0,6455.0,1.0,7.0,278.0,230.0,28.0,34.0,8.000000e+12,0.0,NaN

In [24]:

# Convertir el tipo de datos de la columna 'PROVINCIA_CODIGO' a string en el DataFrame 'cne2002resultadosV1'
cne2002resultadosV1['PROVINCIA_CODIGO'] = cne2002resultadosV1['PROVINCIA_CODIGO'].astype(str)

# Limpiar las claves del diccionario 'mapeo_csv' y los valores de la columna 'PROVINCIA_CODIGO'
mapeo_csv = dict(zip(diccionario_csv['PROVINCIA_CODIGO'].astype(str), diccionario_csv['PROVINCIA_NOMBRE']))

# Mapear los códigos de provincia del DataFrame 'cne2002resultadosV1' utilizando el diccionario CSV
cne2002resultadosV1['PROVINCIA_CODIGO'] = cne2002resultadosV1['PROVINCIA_CODIGO'].map(mapeo_csv)

#capitalizar todas las palabras de la columna 'PROVINCIA_CODIGO'
cne2002resultadosV1['PROVINCIA_CODIGO'] = cne2002resultadosV1['PROVINCIA_CODIGO'].str.title()

# Cargar el diccionario estandarizado 'provincias.tsv' en un DataFrame
diccionario_estandarizado = pd.read_csv('../diccionarios estandar/provincias.tsv', sep='\t')
# Crear un diccionario de mapeo de código a nombre de provincia del diccionario estandarizado
mapeo_estandarizado = dict(zip(diccionario_estandarizado['provincia'], diccionario_estandarizado['cod_provincia']))

# Mapear los códigos de provincia del DataFrame 'cne2002resultadosV1' utilizando el diccionario estandarizado
cne2002resultadosV1['PROVINCIA_CODIGO'] = cne2002resultadosV1['PROVINCIA_CODIGO'].map(mapeo_estandarizado)

In [25]:
cne2002resultadosV1

,DIGNIDAD_CODIGO,PROVINCIA_CODIGO,CANTON_CODIGO,PARROQUIA_CODIGO,SEXO,NUMERO_DE_ACTAS,VOTOS_EN_BLANCO,VOTOS_NULOS,OP_CODIGO,OP_VOTOS_EN_PLANCHA,CANDIDATO_CODIGO,CANDIDATO_VOTOS,CANDIDATO_ESTADO
0,1.0,P1,260.0,285.0,2.0,31.0,204.0,381.0,201.0,0.0,1.000000e+12,59.0,NaN
1,1.0,P1,260.0,285.0,2.0,31.0,204.0,381.0,202.0,0.0,1.000000e+12,637.0,1.0
2,1.0,P1,260.0,285.0,2.0,31.0,204.0,381.0,6.0,0.0,1.000000e+12,111.0,NaN
3,1.0,P1,260.0,285.0,2.0,31.0,204.0,381.0,7.0,0.0,1.000000e+12,337.0,NaN
4,1.0,P1,260.0,285.0,2.0,31.0,204.0,381.0,10.0,0.0,1.000000e+12,142.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
642941,8.0,P22,935.0,6455.0,1.0,7.0,278.0,230.0,28.0,34.0,8.000000e+12,0.0,NaN
642942,8.0,P22,935.0,6455.0,1.0,7.0,278.0,230.0,28.0,34.0,8.000000e+12,0.0,NaN
642943,8.0,P22,935.0,6455.0,1.0,7.0,278.0,230.0,28.0,34.0,8.000000e+12,0.0,NaN
642944,8.0,P22,935.0,6455.0,1.0,7.0,278.0,230.0,28.0,34.0,8.000000e+12,0.0,NaN
642945,8.0,P22,935.0,6455.0,1.0,7.0,278.0,230.0,28.0,34.0,8.000000e+12,0.0,NaN

In [26]:
cne2002resultadosV1["DIGNIDAD_CODIGO"] = cne2002resultadosV1["DIGNIDAD_CODIGO"].astype(int)
cne2002resultadosV1["SEXO"] = cne2002resultadosV1["SEXO"].astype(int)
cne2002resultadosV1["NUMERO_DE_ACTAS"] = cne2002resultadosV1["NUMERO_DE_ACTAS"].astype(int)
cne2002resultadosV1["VOTOS_EN_BLANCO"] = cne2002resultadosV1["VOTOS_EN_BLANCO"].astype(int)
cne2002resultadosV1["VOTOS_NULOS"] = cne2002resultadosV1["VOTOS_NULOS"].astype(int)
cne2002resultadosV1["CANDIDATO_VOTOS"] = cne2002resultadosV1["CANDIDATO_VOTOS"].astype(int)

#filtrar por dignidad igual a 1
cne2002resultadosV1=cne2002resultadosV1[cne2002resultadosV1['DIGNIDAD_CODIGO']==1.0]

In [27]:
cne2002resultadosV1

,DIGNIDAD_CODIGO,PROVINCIA_CODIGO,CANTON_CODIGO,PARROQUIA_CODIGO,SEXO,NUMERO_DE_ACTAS,VOTOS_EN_BLANCO,VOTOS_NULOS,OP_CODIGO,OP_VOTOS_EN_PLANCHA,CANDIDATO_CODIGO,CANDIDATO_VOTOS,CANDIDATO_ESTADO
0,1,P1,260.0,285.0,2,31,204,381,201.0,0.0,1.000000e+12,59,NaN
1,1,P1,260.0,285.0,2,31,204,381,202.0,0.0,1.000000e+12,637,1.0
2,1,P1,260.0,285.0,2,31,204,381,6.0,0.0,1.000000e+12,111,NaN
3,1,P1,260.0,285.0,2,31,204,381,7.0,0.0,1.000000e+12,337,NaN
4,1,P1,260.0,285.0,2,31,204,381,10.0,0.0,1.000000e+12,142,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25537,1,P22,935.0,6455.0,1,7,87,144,12.0,0.0,1.000000e+12,118,NaN
25538,1,P22,935.0,6455.0,1,7,87,144,22.0,0.0,1.000000e+12,4,NaN
25539,1,P22,935.0,6455.0,1,7,87,144,24.0,0.0,1.000000e+12,3,NaN
25540,1,P22,935.0,6455.0,1,7,87,144,28.0,0.0,1.000000e+12,151,NaN
25541,1,P22,935.0,6455.0,1,7,87,144,40.0,0.0,1.000000e+12,13,NaN

In [28]:
# agrupación para nivel nacional
cne2002agV1 = cne2002resultadosV1.groupby(['CANTON_CODIGO','CANDIDATO_CODIGO', 'SEXO',]).agg({
    'NUMERO_DE_ACTAS': 'sum',
    'VOTOS_EN_BLANCO': 'sum',
    'VOTOS_NULOS': 'sum',
    'CANDIDATO_VOTOS': 'sum'
}).reset_index()
# Crear una columna que muestre la descripción del SEXO
#cne2002agV1['SEXO_DESCRIPCION'] = cne2002agV1['SEXO'].map({1: 'MASCULINO', 2: 'FEMENINO'})
#cne2002agV1.drop(columns=['SEXO'],inplace=True)

In [29]:
cne2002agV1

,CANTON_CODIGO,CANDIDATO_CODIGO,SEXO,NUMERO_DE_ACTAS,VOTOS_EN_BLANCO,VOTOS_NULOS,CANDIDATO_VOTOS
0,5.0,1.000000e+12,1,92,470,1260,231
1,5.0,1.000000e+12,2,93,619,1326,402
2,5.0,1.000000e+12,1,92,470,1260,3580
3,5.0,1.000000e+12,2,93,619,1326,3614
4,5.0,1.000000e+12,1,92,470,1260,773
...,...,...,...,...,...,...,...
4769,995.0,1.000000e+12,2,9,100,98,24
4770,995.0,1.000000e+12,1,10,94,97,7
4771,995.0,1.000000e+12,2,9,100,98,4
4772,995.0,1.000000e+12,1,10,94,97,134
4773,995.0,1.000000e+12,2,9,100,98,144

In [30]:
# Crear columnas separadas
cne2002agV1['VOTOS_NULOS_M'] = cne2002agV1.loc[cne2002agV1['SEXO'] == 1 , 'VOTOS_NULOS']
cne2002agV1['VOTOS_NULOS_F'] = cne2002agV1.loc[cne2002agV1['SEXO'] == 2 , 'VOTOS_NULOS']

# Llenar con NaN en caso de que no haya datos para una categoría
cne2002agV1['VOTOS_NULOS_M'] = cne2002agV1['VOTOS_NULOS_M'].fillna(0)
cne2002agV1['VOTOS_NULOS_F'] = cne2002agV1['VOTOS_NULOS_F'].fillna(0)

cne2002agV1 = cne2002agV1.drop("VOTOS_NULOS", axis=1)

# Crear columnas separadas
cne2002agV1['VOTOS_BLANCOS_M'] = cne2002agV1.loc[cne2002agV1['SEXO'] == 1 , 'VOTOS_EN_BLANCO']
cne2002agV1['VOTOS_BLANCOS_F'] = cne2002agV1.loc[cne2002agV1['SEXO'] == 2 , 'VOTOS_EN_BLANCO']

# Llenar con NaN en caso de que no haya datos para una categoría
cne2002agV1['VOTOS_BLANCOS_M'] = cne2002agV1['VOTOS_BLANCOS_M'].fillna(0)
cne2002agV1['VOTOS_BLANCOS_F'] = cne2002agV1['VOTOS_BLANCOS_F'].fillna(0)

cne2002agV1 = cne2002agV1.drop("VOTOS_EN_BLANCO", axis=1)

# Crear columnas separadas
cne2002agV1['VOTOS_CANDIDATO_M'] = cne2002agV1.loc[cne2002agV1['SEXO'] == 1 , 'CANDIDATO_VOTOS']
cne2002agV1['VOTOS_CANDIDATO_F'] = cne2002agV1.loc[cne2002agV1['SEXO'] == 2 , 'CANDIDATO_VOTOS']

# Llenar con NaN en caso de que no haya datos para una categoría
cne2002agV1['VOTOS_CANDIDATO_M'] = cne2002agV1['VOTOS_CANDIDATO_M'].fillna(0)
cne2002agV1['VOTOS_CANDIDATO_F'] = cne2002agV1['VOTOS_CANDIDATO_F'].fillna(0)

cne2002agV1 = cne2002agV1.drop("CANDIDATO_VOTOS", axis=1)

In [31]:
cne2002agV1

,CANTON_CODIGO,CANDIDATO_CODIGO,SEXO,NUMERO_DE_ACTAS,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,VOTOS_CANDIDATO_M,VOTOS_CANDIDATO_F
0,5.0,1.000000e+12,1,92,1260.0,0.0,470.0,0.0,231.0,0.0
1,5.0,1.000000e+12,2,93,0.0,1326.0,0.0,619.0,0.0,402.0
2,5.0,1.000000e+12,1,92,1260.0,0.0,470.0,0.0,3580.0,0.0
3,5.0,1.000000e+12,2,93,0.0,1326.0,0.0,619.0,0.0,3614.0
4,5.0,1.000000e+12,1,92,1260.0,0.0,470.0,0.0,773.0,0.0
...,...,...,...,...,...,...,...,...,...,...
4769,995.0,1.000000e+12,2,9,0.0,98.0,0.0,100.0,0.0,24.0
4770,995.0,1.000000e+12,1,10,97.0,0.0,94.0,0.0,7.0,0.0
4771,995.0,1.000000e+12,2,9,0.0,98.0,0.0,100.0,0.0,4.0
4772,995.0,1.000000e+12,1,10,97.0,0.0,94.0,0.0,134.0,0.0
4773,995.0,1.000000e+12,2,9,0.0,98.0,0.0,100.0,0.0,144.0

In [32]:
cne2002agV1 = cne2002agV1.drop("SEXO", axis=1)

In [33]:
cne2002agFV1 = cne2002agV1.groupby(['CANTON_CODIGO','CANDIDATO_CODIGO']).agg({
    'NUMERO_DE_ACTAS': 'sum',
    'VOTOS_NULOS_M': 'sum',
    'VOTOS_NULOS_F': 'sum',
    'VOTOS_BLANCOS_M': 'sum',
     'VOTOS_BLANCOS_F': 'sum',
    'VOTOS_CANDIDATO_M': 'sum',
    'VOTOS_CANDIDATO_F': 'sum'

}).reset_index()

cne2002agFV1

,CANTON_CODIGO,CANDIDATO_CODIGO,NUMERO_DE_ACTAS,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,VOTOS_CANDIDATO_M,VOTOS_CANDIDATO_F
0,5.0,1.000000e+12,185,1260.0,1326.0,470.0,619.0,231.0,402.0
1,5.0,1.000000e+12,185,1260.0,1326.0,470.0,619.0,3580.0,3614.0
2,5.0,1.000000e+12,185,1260.0,1326.0,470.0,619.0,773.0,810.0
3,5.0,1.000000e+12,185,1260.0,1326.0,470.0,619.0,5924.0,6090.0
4,5.0,1.000000e+12,185,1260.0,1326.0,470.0,619.0,978.0,826.0
...,...,...,...,...,...,...,...,...,...
2382,995.0,1.000000e+12,19,97.0,98.0,94.0,100.0,406.0,406.0
2383,995.0,1.000000e+12,19,97.0,98.0,94.0,100.0,12.0,6.0
2384,995.0,1.000000e+12,19,97.0,98.0,94.0,100.0,14.0,24.0
2385,995.0,1.000000e+12,19,97.0,98.0,94.0,100.0,7.0,4.0
2386,995.0,1.000000e+12,19,97.0,98.0,94.0,100.0,134.0,144.0

In [34]:
# Agregar la columna "AÑO" con valor 2004 al principio del dataframe
cne2002agFV1.insert(0, "AÑO", 2002)

# Agregar la columna "VUELTA" con valor 2 al principio del dataframe
cne2002agFV1.insert(1, "VUELTA", 1)

In [35]:
cne2002agFV1

,AÑO,VUELTA,CANTON_CODIGO,CANDIDATO_CODIGO,NUMERO_DE_ACTAS,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,VOTOS_CANDIDATO_M,VOTOS_CANDIDATO_F
0,2002,1,5.0,1.000000e+12,185,1260.0,1326.0,470.0,619.0,231.0,402.0
1,2002,1,5.0,1.000000e+12,185,1260.0,1326.0,470.0,619.0,3580.0,3614.0
2,2002,1,5.0,1.000000e+12,185,1260.0,1326.0,470.0,619.0,773.0,810.0
3,2002,1,5.0,1.000000e+12,185,1260.0,1326.0,470.0,619.0,5924.0,6090.0
4,2002,1,5.0,1.000000e+12,185,1260.0,1326.0,470.0,619.0,978.0,826.0
...,...,...,...,...,...,...,...,...,...,...,...
2382,2002,1,995.0,1.000000e+12,19,97.0,98.0,94.0,100.0,406.0,406.0
2383,2002,1,995.0,1.000000e+12,19,97.0,98.0,94.0,100.0,12.0,6.0
2384,2002,1,995.0,1.000000e+12,19,97.0,98.0,94.0,100.0,14.0,24.0
2385,2002,1,995.0,1.000000e+12,19,97.0,98.0,94.0,100.0,7.0,4.0
2386,2002,1,995.0,1.000000e+12,19,97.0,98.0,94.0,100.0,134.0,144.0

### Registro Electoral 2002 (CNE)
Analizar el archivo "registro electoral a nivel parroquial 2002.sav" para obtener el número de electores por canton.

In [36]:
cne2002RPA, meta = py.read_sav("../raw/registro electoral/registro electoral a nivel parroquial 2002.sav")
cne2002RPA

,PROVINCIA_CODIGO,CANTON_CODIGO,PARROQUIA_CODIGO,SEXO,GRANDES_GRUPOS_DE_EDAD_1V,ELECTORES
0,1.0,260.0,285.0,1.0,2.0,5531.0
1,1.0,260.0,285.0,1.0,3.0,519.0
2,1.0,260.0,285.0,2.0,2.0,5582.0
3,1.0,260.0,285.0,2.0,3.0,541.0
4,1.0,260.0,730.0,1.0,2.0,1880.0
...,...,...,...,...,...,...
4613,22.0,935.0,3480.0,2.0,3.0,5.0
4614,22.0,935.0,6455.0,1.0,2.0,1919.0
4615,22.0,935.0,6455.0,1.0,3.0,94.0
4616,22.0,935.0,6455.0,2.0,2.0,1549.0
4617,22.0,935.0,6455.0,2.0,3.0,56.0

In [37]:
cne2002RPA = cne2002RPA.groupby(['CANTON_CODIGO', 'SEXO' ]).agg({
    'ELECTORES': 'sum',

}).reset_index()

cne2002RPA

     CANTON_CODIGO  SEXO  ELECTORES
0              5.0   1.0    26308.0
1              5.0   2.0    26757.0
2             10.0   1.0    10646.0
3             10.0   2.0    11151.0
4             15.0   1.0     5195.0
..             ...   ...        ...
429          986.0   2.0     2156.0
430          990.0   1.0     1104.0
431          990.0   2.0     1192.0
432          995.0   1.0     2603.0
433          995.0   2.0     2507.0

[434 rows x 3 columns]

In [38]:
# Crear columnas separadas
cne2002RPA['ELECTORES_M'] = cne2002RPA.loc[cne2002RPA['SEXO'] == 1 , 'ELECTORES']
cne2002RPA['ELECTORAS_F'] = cne2002RPA.loc[cne2002RPA['SEXO'] == 2 , 'ELECTORES']

# Llenar con NaN en caso de que no haya datos para una categoría
cne2002RPA['ELECTORES_M'] = cne2002RPA['ELECTORES_M'].fillna(0)
cne2002RPA['ELECTORAS_F'] = cne2002RPA['ELECTORAS_F'].fillna(0)

cne2002RPA = cne2002RPA.drop("ELECTORES", axis=1)

cne2002RPA

     CANTON_CODIGO  SEXO  ELECTORES_M  ELECTORAS_F
0              5.0   1.0      26308.0          0.0
1              5.0   2.0          0.0      26757.0
2             10.0   1.0      10646.0          0.0
3             10.0   2.0          0.0      11151.0
4             15.0   1.0       5195.0          0.0
..             ...   ...          ...          ...
429          986.0   2.0          0.0       2156.0
430          990.0   1.0       1104.0          0.0
431          990.0   2.0          0.0       1192.0
432          995.0   1.0       2603.0          0.0
433          995.0   2.0          0.0       2507.0

[434 rows x 4 columns]

In [39]:
cne2002RPA.drop('SEXO', axis=1)
cne2002RPA = cne2002RPA.groupby(['CANTON_CODIGO']).agg({
    'ELECTORES_M': 'sum',
    'ELECTORAS_F': 'sum'

}).reset_index()

cne2002RPA

     CANTON_CODIGO  ELECTORES_M  ELECTORAS_F
0              5.0      26308.0      26757.0
1             10.0      10646.0      11151.0
2             15.0       5195.0       5475.0
3             20.0       4530.0       4469.0
4             25.0       5210.0       5034.0
..             ...          ...          ...
212          980.0       2489.0       2270.0
213          985.0       3076.0       2789.0
214          986.0       2424.0       2156.0
215          990.0       1104.0       1192.0
216          995.0       2603.0       2507.0

[217 rows x 3 columns]

### Listado de Candidatos

In [40]:
#importar la base de datos de candidatos
cne2002candidatosV1, meta = py.read_sav("../raw/organizaciones politicas/CANDIDATOS (1).sav")

In [41]:
cne2002candidatosV1

,DIGNIDAD_CODIGO,DIGNIDAD_NOMBRE,CANDIDATO_PROVINCIA_CODIGO,CANDIDATO_PROVINCIA_NOMBRE,CANDIDATO_CANTON_CODIGO,CANDIDATO_CANTON_NOMBRE,OP_CODIGO,CANDIDATO_CODIGO,CANDIDATO_NOMBRE,CANDIDATO_SEXO,CANDIDATO_EDAD,CANDIDATO_ORDEN_LISTA,SUPLENTE1_NOMBRE,SUPLENTE1_SEXO,SUPLENTE1_EDAD,SUPLENTE2_NOMBRE,SUPLENTE2_SEXO,SUPLENTE2_EDAD,CANDIDATO_ESTADO
0,4.0,4.0,14.0,14.0,796.0,796.0,1.800000e+01,4.147960e+12,ANTUNI CATANI RAFAEL DOMINGO,1.0,41.0,1.0,,NaN,NaN,,NaN,NaN,0.0
1,4.0,4.0,1.0,1.0,556.0,556.0,1.556000e+10,4.015560e+12,CEDILLO GUAMAN ELMER JORGE,1.0,41.0,1.0,,NaN,NaN,,NaN,NaN,0.0
2,4.0,4.0,1.0,1.0,556.0,556.0,1.556000e+10,4.015560e+12,SANCHEZ DELGADO ALCIDES GILBERTO,1.0,43.0,1.0,,NaN,NaN,,NaN,NaN,0.0
3,4.0,4.0,1.0,1.0,556.0,556.0,1.556000e+10,4.015560e+12,MALDONADO ESPARZA JORGE EDUARDO,1.0,44.0,1.0,,NaN,NaN,,NaN,NaN,0.0
4,4.0,4.0,1.0,1.0,556.0,556.0,2.100000e+01,4.015560e+12,BERREZUETA PESANTEZ LUIS MARCO,1.0,45.0,1.0,,NaN,NaN,,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9475,8.0,8.0,0.0,0.0,0.0,0.0,1.000000e+01,8.000000e+12,SOLORZANO CONSTANTINE HECTOR CARLOS,1.0,65.0,1.0,GAIBORT BURGOS ANGEL ALBERTO,1.0,43.0,HIDALGO VILLACIS CARLOS ALBERTO,1.0,67.0,1.0
9476,8.0,8.0,0.0,0.0,0.0,0.0,6.000000e+00,8.000000e+12,PEÑAHERRERA PADILLA BLASCO MANUEL,1.0,68.0,1.0,BUITRON CARRERA XAVIER EDUARDO,1.0,39.0,DAVILA ANDRADE OSWALDO VICENTE,1.0,73.0,1.0
9477,8.0,8.0,0.0,0.0,0.0,0.0,7.000000e+00,8.000000e+12,FANTONI CAMBA JORGE VICENTE,1.0,68.0,1.0,CLERY AGUIRRE ARTURO GUILLERMO,1.0,26.0,GARZON ZAPATA ANGEL TOMAS,1.0,49.0,1.0
9478,8.0,8.0,0.0,0.0,0.0,0.0,2.100000e+01,8.000000e+12,EHLERS ZURITA FREDDY ARTURO,1.0,56.0,1.0,JALKH ROBEN CHARBEL GUSTAVO,1.0,35.0,PEREZ BORJA MONICA,2.0,35.0,1.0
9479,8.0,8.0,0.0,0.0,0.0,0.0,6.000000e+00,8.000000e+12,VALLEJO KLAERE JUANA MARIA,2.0,56.0,2.0,CORDERO LEON GUADALUPE VILMA,2.0,66.0,BATTEL ZAMBRANO REGINA EMILIA,2.0,42.0,1.0

In [42]:
#Crear un nuevo dataframe con las columnas deseadas
cne2002c = cne2002candidatosV1[['OP_CODIGO', 'CANDIDATO_CODIGO', 'CANDIDATO_NOMBRE', 'CANDIDATO_SEXO', 'CANDIDATO_EDAD','DIGNIDAD_CODIGO']].copy()

cne2002c["CANDIDATO_SEXO"] = cne2002c["CANDIDATO_SEXO"].replace(1.0, "MASCULINO")
cne2002c["CANDIDATO_SEXO"] = cne2002c["CANDIDATO_SEXO"].replace(2.0, "FEMENINO")

# Convertir el tipo de datos de la columna 'OP_CODIGO' a string en el DataFrame 'cne2002c'
cne2002c["DIGNIDAD_CODIGO"] = cne2002c["DIGNIDAD_CODIGO"].astype(int)

cne2002c["CANDIDATO_EDAD"] = cne2002c["CANDIDATO_EDAD"].astype(int)

cne2002c["OP_CODIGO"] = cne2002c["OP_CODIGO"].astype(int)
# no castear como int porque sucede un overflow
#cne2002c["CANDIDATO_CODIGO"] = cne2002c["CANDIDATO_CODIGO"].astype(int)

#Filtrar por candidatos a presidente (Digindad 1)
cne2002c=cne2002c[cne2002candidatosV1['DIGNIDAD_CODIGO']==1.0]

In [43]:
# Mostrar el nuevo dataframe
cne2002c.columns

Index(['OP_CODIGO', 'CANDIDATO_CODIGO', 'CANDIDATO_NOMBRE', 'CANDIDATO_SEXO',
       'CANDIDATO_EDAD', 'DIGNIDAD_CODIGO'],
      dtype='object')

In [44]:
cne2002agFV1['CANDIDATO_CODIGO'] = cne2002agFV1['CANDIDATO_CODIGO'].astype(float)
cne2002c['CANDIDATO_CODIGO'] = cne2002c['CANDIDATO_CODIGO'].astype(float)

In [45]:
cne2002agFV1['CANDIDATO_NOMBRE'] = cne2002agFV1['CANDIDATO_CODIGO'].map(cne2002c.set_index('CANDIDATO_CODIGO')['CANDIDATO_NOMBRE'])
cne2002agFV1['CANDIDATO_EDAD'] = cne2002agFV1['CANDIDATO_CODIGO'].map(cne2002c.set_index('CANDIDATO_CODIGO')['CANDIDATO_EDAD'])
cne2002agFV1['CANDIDATO_SEXO'] = cne2002agFV1['CANDIDATO_CODIGO'].map(cne2002c.set_index('CANDIDATO_CODIGO')['CANDIDATO_SEXO'])
cne2002agFV1['OP_CODIGO'] = cne2002agFV1['CANDIDATO_CODIGO'].map(cne2002c.set_index('CANDIDATO_CODIGO')['OP_CODIGO'])

cne2002agFV1

,AÑO,VUELTA,CANTON_CODIGO,CANDIDATO_CODIGO,NUMERO_DE_ACTAS,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,VOTOS_CANDIDATO_M,VOTOS_CANDIDATO_F,CANDIDATO_NOMBRE,CANDIDATO_EDAD,CANDIDATO_SEXO,OP_CODIGO
0,2002,1,5.0,1.000000e+12,185,1260.0,1326.0,470.0,619.0,231.0,402.0,JUEZ ABUCHAKRA IVONNE LEYLA,51,FEMENINO,201
1,2002,1,5.0,1.000000e+12,185,1260.0,1326.0,470.0,619.0,3580.0,3614.0,GUTIERREZ BORBUA LUCIO EDWIN,45,MASCULINO,202
2,2002,1,5.0,1.000000e+12,185,1260.0,1326.0,470.0,619.0,773.0,810.0,NEIRA MENENDEZ ANTONIO XAVIER,55,MASCULINO,6
3,2002,1,5.0,1.000000e+12,185,1260.0,1326.0,470.0,619.0,5924.0,6090.0,NOBOA PONTON ALVARO FERNANDO,51,MASCULINO,7
4,2002,1,5.0,1.000000e+12,185,1260.0,1326.0,470.0,619.0,978.0,826.0,BUCARAM ORTIZ JACOBO,55,MASCULINO,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2382,2002,1,995.0,1.000000e+12,19,97.0,98.0,94.0,100.0,406.0,406.0,BORJA CEVALLOS RODRIGO,67,MASCULINO,12
2383,2002,1,995.0,1.000000e+12,19,97.0,98.0,94.0,100.0,12.0,6.0,VELAZQUEZ HERRERA JACINTO,63,MASCULINO,22
2384,2002,1,995.0,1.000000e+12,19,97.0,98.0,94.0,100.0,14.0,24.0,HURTADO LARREA OSVALDO,63,MASCULINO,24
2385,2002,1,995.0,1.000000e+12,19,97.0,98.0,94.0,100.0,7.0,4.0,VARGAS GUATATUCA CARLOS ANTONIO,43,MASCULINO,28
2386,2002,1,995.0,1.000000e+12,19,97.0,98.0,94.0,100.0,134.0,144.0,ROLDOS AGUILERA LEON,60,MASCULINO,40

In [46]:
cne2002agFV1['CANTON_CODIGO'] = cne2002agFV1['CANTON_CODIGO'].astype(int)
cne2002RPA['CANTON_CODIGO'] = cne2002RPA['CANTON_CODIGO'].astype(int)

In [47]:
cne2002agFV1['ELECTORES_M'] = cne2002agFV1['CANTON_CODIGO'].map(cne2002RPA.set_index('CANTON_CODIGO')['ELECTORES_M'])
cne2002agFV1['ELECTORAS_F'] = cne2002agFV1['CANTON_CODIGO'].map(cne2002RPA.set_index('CANTON_CODIGO')['ELECTORAS_F'])

cne2002agFV1

,AÑO,VUELTA,CANTON_CODIGO,CANDIDATO_CODIGO,NUMERO_DE_ACTAS,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,VOTOS_CANDIDATO_M,VOTOS_CANDIDATO_F,CANDIDATO_NOMBRE,CANDIDATO_EDAD,CANDIDATO_SEXO,OP_CODIGO,ELECTORES_M,ELECTORAS_F
0,2002,1,5,1.000000e+12,185,1260.0,1326.0,470.0,619.0,231.0,402.0,JUEZ ABUCHAKRA IVONNE LEYLA,51,FEMENINO,201,26308.0,26757.0
1,2002,1,5,1.000000e+12,185,1260.0,1326.0,470.0,619.0,3580.0,3614.0,GUTIERREZ BORBUA LUCIO EDWIN,45,MASCULINO,202,26308.0,26757.0
2,2002,1,5,1.000000e+12,185,1260.0,1326.0,470.0,619.0,773.0,810.0,NEIRA MENENDEZ ANTONIO XAVIER,55,MASCULINO,6,26308.0,26757.0
3,2002,1,5,1.000000e+12,185,1260.0,1326.0,470.0,619.0,5924.0,6090.0,NOBOA PONTON ALVARO FERNANDO,51,MASCULINO,7,26308.0,26757.0
4,2002,1,5,1.000000e+12,185,1260.0,1326.0,470.0,619.0,978.0,826.0,BUCARAM ORTIZ JACOBO,55,MASCULINO,10,26308.0,26757.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2382,2002,1,995,1.000000e+12,19,97.0,98.0,94.0,100.0,406.0,406.0,BORJA CEVALLOS RODRIGO,67,MASCULINO,12,2603.0,2507.0
2383,2002,1,995,1.000000e+12,19,97.0,98.0,94.0,100.0,12.0,6.0,VELAZQUEZ HERRERA JACINTO,63,MASCULINO,22,2603.0,2507.0
2384,2002,1,995,1.000000e+12,19,97.0,98.0,94.0,100.0,14.0,24.0,HURTADO LARREA OSVALDO,63,MASCULINO,24,2603.0,2507.0
2385,2002,1,995,1.000000e+12,19,97.0,98.0,94.0,100.0,7.0,4.0,VARGAS GUATATUCA CARLOS ANTONIO,43,MASCULINO,28,2603.0,2507.0
2386,2002,1,995,1.000000e+12,19,97.0,98.0,94.0,100.0,134.0,144.0,ROLDOS AGUILERA LEON,60,MASCULINO,40,2603.0,2507.0

### Análizar Organizaciones Políticas

In [48]:
# Crear un nuevo dataframe a partir del archivo 'organizaciones_politicas_2002.sav'
cne2002op, meta = py.read_sav("../raw/organizaciones politicas/organizaciones_politicas_2002.sav")

In [49]:
cne2002op

,OP_CODIGO,OP_PROVINCIA_CODIGO,OP_CANTON_CODIGO,OP_PARROQUIA_CODIGO,OP_TIPO,OP_AMBITO,OP_NOMBRE,OP_SIGLAS,OP_LISTA
0,1.000000e+00,0.0,0.0,0.0,PARTIDOS POLITICOS,NACIONAL,PARTIDO UNION NACIONAL UNO,UN - UNO,1
1,2.000000e+00,0.0,0.0,0.0,PARTIDOS POLITICOS,NACIONAL,PARTIDO LIBERAL RADICAL ECUATORIANO,PLRE,2
2,3.000000e+00,0.0,0.0,0.0,PARTIDOS POLITICOS,NACIONAL,PARTIDO SOCIEDAD PATRIOTICA 21 DE ENERO,PSP,3
3,4.000000e+00,0.0,0.0,0.0,PARTIDOS POLITICOS,NACIONAL,PARTIDO CONCENTRACION DE FUERZAS POPULARES,CFP,4
4,5.000000e+00,0.0,0.0,0.0,PARTIDOS POLITICOS,NACIONAL,PARTIDO DEMOCRACIA POPULAR - UNION DEMOCRATA C...,DP-UDC,5
...,...,...,...,...,...,...,...,...,...
175,2.200000e+11,22.0,0.0,0.0,ALIANZAS,ALIANZA,ALIANZA UNION NACIONAL - UNO/ CONCENTRACION DE...,UN - UNO/CFP,1-4
176,2.200000e+11,22.0,0.0,0.0,ALIANZAS,ALIANZA,ALIANZA IZQUIERDA DEMOCRATICA/MOVIMIENTO CIUDA...,ID /MCNP,12-21
177,2.200000e+11,22.0,0.0,0.0,ALIANZAS,ALIANZA,ALIANZA INTEGRACIÓN MUSHUK INTI,AN /PS-FA /DP-UDC,14-17-5
178,2.200000e+11,22.0,0.0,0.0,ALIANZAS,ALIANZA,ALIANZA MOVIMIENTO DE INTEGRACION PROVINCIAL/P...,MIP /PRE,42-10
179,2.264500e+11,22.0,645.0,0.0,ALIANZAS,ALIANZA,ALIANZA INTEGRACION MUSHUK INTI,AN /PS-FA /DP-UDC/MIAJ,14-17-5-28

In [50]:
cne2002agFV1['OP_TIPO'] = cne2002agFV1['OP_CODIGO'].map(cne2002op.set_index('OP_CODIGO')['OP_TIPO'])
cne2002agFV1['OP_AMBITO'] = cne2002agFV1['OP_CODIGO'].map(cne2002op.set_index('OP_CODIGO')['OP_AMBITO'])
cne2002agFV1['OP_NOMBRE'] = cne2002agFV1['OP_CODIGO'].map(cne2002op.set_index('OP_CODIGO')['OP_NOMBRE'])
cne2002agFV1['OP_SIGLAS'] = cne2002agFV1['OP_CODIGO'].map(cne2002op.set_index('OP_CODIGO')['OP_SIGLAS'])

cne2002agFV1

,AÑO,VUELTA,CANTON_CODIGO,CANDIDATO_CODIGO,NUMERO_DE_ACTAS,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,VOTOS_CANDIDATO_M,...,CANDIDATO_NOMBRE,CANDIDATO_EDAD,CANDIDATO_SEXO,OP_CODIGO,ELECTORES_M,ELECTORAS_F,OP_TIPO,OP_AMBITO,OP_NOMBRE,OP_SIGLAS
0,2002,1,5,1.000000e+12,185,1260.0,1326.0,470.0,619.0,231.0,...,JUEZ ABUCHAKRA IVONNE LEYLA,51,FEMENINO,201,26308.0,26757.0,ALIANZAS,ALIANZA,PARTIDO LIBERAL RADICAL ECUATORIANO/MOVIMIENTO...,PLRE/META
1,2002,1,5,1.000000e+12,185,1260.0,1326.0,470.0,619.0,3580.0,...,GUTIERREZ BORBUA LUCIO EDWIN,45,MASCULINO,202,26308.0,26757.0,ALIANZAS,ALIANZA,PARTIDO SOCIEDAD PATRIOTICA 21 DE ENERO/MOVIMI...,PSP/MUPP-NP
2,2002,1,5,1.000000e+12,185,1260.0,1326.0,470.0,619.0,773.0,...,NEIRA MENENDEZ ANTONIO XAVIER,55,MASCULINO,6,26308.0,26757.0,PARTIDOS POLITICOS,NACIONAL,PARTIDO SOCIAL CRISTIANO,PSC
3,2002,1,5,1.000000e+12,185,1260.0,1326.0,470.0,619.0,5924.0,...,NOBOA PONTON ALVARO FERNANDO,51,MASCULINO,7,26308.0,26757.0,PARTIDOS POLITICOS,NACIONAL,PARTIDO RENOVADOR INSTITUCIONAL ACCION NACIONAL,PRIAN
4,2002,1,5,1.000000e+12,185,1260.0,1326.0,470.0,619.0,978.0,...,BUCARAM ORTIZ JACOBO,55,MASCULINO,10,26308.0,26757.0,PARTIDOS POLITICOS,NACIONAL,PARTIDO ROLDOSISTA ECUATORIANO,PRE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2382,2002,1,995,1.000000e+12,19,97.0,98.0,94.0,100.0,406.0,...,BORJA CEVALLOS RODRIGO,67,MASCULINO,12,2603.0,2507.0,PARTIDOS POLITICOS,NACIONAL,PARTIDO IZQUIERDA DEMOCRATICA,ID
2383,2002,1,995,1.000000e+12,19,97.0,98.0,94.0,100.0,12.0,...,VELAZQUEZ HERRERA JACINTO,63,MASCULINO,22,2603.0,2507.0,MOVIMIENTOS NACIONALES,NACIONAL,MOVIMIENTO TRANSFORMACION SOCIAL INDEPENDIENTE,TSI
2384,2002,1,995,1.000000e+12,19,97.0,98.0,94.0,100.0,14.0,...,HURTADO LARREA OSVALDO,63,MASCULINO,24,2603.0,2507.0,MOVIMIENTOS NACIONALES,NACIONAL,MOVIMIENTO PATRIA SOLIDARIA,MPS
2385,2002,1,995,1.000000e+12,19,97.0,98.0,94.0,100.0,7.0,...,VARGAS GUATATUCA CARLOS ANTONIO,43,MASCULINO,28,2603.0,2507.0,MOVIMIENTOS NACIONALES,NACIONAL,MOVIMIENTO INDEPENDIENTE AMAUTA JATARI,MIAJ
2386,2002,1,995,1.000000e+12,19,97.0,98.0,94.0,100.0,134.0,...,ROLDOS AGUILERA LEON,60,MASCULINO,40,2603.0,2507.0,MOVIMIENTOS NACIONALES,NACIONAL,BINOMIO ROLDOS PADILLA,RP

In [51]:

cne2002agFV1['OP_CODIGO'] = cne2002agFV1['OP_CODIGO'].astype(int)

In [52]:
# Mostrar el DataFrame resultante
cne2002agFV1.columns

Index(['AÑO', 'VUELTA', 'CANTON_CODIGO', 'CANDIDATO_CODIGO', 'NUMERO_DE_ACTAS',
       'VOTOS_NULOS_M', 'VOTOS_NULOS_F', 'VOTOS_BLANCOS_M', 'VOTOS_BLANCOS_F',
       'VOTOS_CANDIDATO_M', 'VOTOS_CANDIDATO_F', 'CANDIDATO_NOMBRE',
       'CANDIDATO_EDAD', 'CANDIDATO_SEXO', 'OP_CODIGO', 'ELECTORES_M',
       'ELECTORAS_F', 'OP_TIPO', 'OP_AMBITO', 'OP_NOMBRE', 'OP_SIGLAS'],
      dtype='object')

In [53]:
cne2002agFV1['CANDIDATO_CODIGO'] = cne2002agFV1['CANDIDATO_CODIGO'].map(cne2002c.set_index('CANDIDATO_CODIGO')['OP_CODIGO'])
cne2002agFV1=cne2002agFV1.rename(columns = {'CANDIDATO_CODIGO':'OP_CODIGO'})

In [54]:
cne2002agFV1

,AÑO,VUELTA,CANTON_CODIGO,OP_CODIGO,NUMERO_DE_ACTAS,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,VOTOS_CANDIDATO_M,...,CANDIDATO_NOMBRE,CANDIDATO_EDAD,CANDIDATO_SEXO,OP_CODIGO,ELECTORES_M,ELECTORAS_F,OP_TIPO,OP_AMBITO,OP_NOMBRE,OP_SIGLAS
0,2002,1,5,201,185,1260.0,1326.0,470.0,619.0,231.0,...,JUEZ ABUCHAKRA IVONNE LEYLA,51,FEMENINO,201,26308.0,26757.0,ALIANZAS,ALIANZA,PARTIDO LIBERAL RADICAL ECUATORIANO/MOVIMIENTO...,PLRE/META
1,2002,1,5,202,185,1260.0,1326.0,470.0,619.0,3580.0,...,GUTIERREZ BORBUA LUCIO EDWIN,45,MASCULINO,202,26308.0,26757.0,ALIANZAS,ALIANZA,PARTIDO SOCIEDAD PATRIOTICA 21 DE ENERO/MOVIMI...,PSP/MUPP-NP
2,2002,1,5,6,185,1260.0,1326.0,470.0,619.0,773.0,...,NEIRA MENENDEZ ANTONIO XAVIER,55,MASCULINO,6,26308.0,26757.0,PARTIDOS POLITICOS,NACIONAL,PARTIDO SOCIAL CRISTIANO,PSC
3,2002,1,5,7,185,1260.0,1326.0,470.0,619.0,5924.0,...,NOBOA PONTON ALVARO FERNANDO,51,MASCULINO,7,26308.0,26757.0,PARTIDOS POLITICOS,NACIONAL,PARTIDO RENOVADOR INSTITUCIONAL ACCION NACIONAL,PRIAN
4,2002,1,5,10,185,1260.0,1326.0,470.0,619.0,978.0,...,BUCARAM ORTIZ JACOBO,55,MASCULINO,10,26308.0,26757.0,PARTIDOS POLITICOS,NACIONAL,PARTIDO ROLDOSISTA ECUATORIANO,PRE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2382,2002,1,995,12,19,97.0,98.0,94.0,100.0,406.0,...,BORJA CEVALLOS RODRIGO,67,MASCULINO,12,2603.0,2507.0,PARTIDOS POLITICOS,NACIONAL,PARTIDO IZQUIERDA DEMOCRATICA,ID
2383,2002,1,995,22,19,97.0,98.0,94.0,100.0,12.0,...,VELAZQUEZ HERRERA JACINTO,63,MASCULINO,22,2603.0,2507.0,MOVIMIENTOS NACIONALES,NACIONAL,MOVIMIENTO TRANSFORMACION SOCIAL INDEPENDIENTE,TSI
2384,2002,1,995,24,19,97.0,98.0,94.0,100.0,14.0,...,HURTADO LARREA OSVALDO,63,MASCULINO,24,2603.0,2507.0,MOVIMIENTOS NACIONALES,NACIONAL,MOVIMIENTO PATRIA SOLIDARIA,MPS
2385,2002,1,995,28,19,97.0,98.0,94.0,100.0,7.0,...,VARGAS GUATATUCA CARLOS ANTONIO,43,MASCULINO,28,2603.0,2507.0,MOVIMIENTOS NACIONALES,NACIONAL,MOVIMIENTO INDEPENDIENTE AMAUTA JATARI,MIAJ
2386,2002,1,995,40,19,97.0,98.0,94.0,100.0,134.0,...,ROLDOS AGUILERA LEON,60,MASCULINO,40,2603.0,2507.0,MOVIMIENTOS NACIONALES,NACIONAL,BINOMIO ROLDOS PADILLA,RP

In [55]:
cne2002agFV1['OP_CODIGO'] = cne2002agFV1['OP_CODIGO'].astype(int)

### Generar columnas de votos por candidato y por género

In [56]:
# Creacion de un diccionario con los nombres de los candidatos y los codigos de sus organizaciones politicas
candidatos_dict = dict(zip(cne2002c['CANDIDATO_NOMBRE'], cne2002c['OP_CODIGO']))

#Imprime el diccionario
print(candidatos_dict)
candidatos_dict

{'BORJA CEVALLOS RODRIGO': 12, 'VELAZQUEZ HERRERA JACINTO': 22, 'VARGAS GUATATUCA CARLOS ANTONIO': 28, 'HURTADO LARREA  OSVALDO': 24, 'ROLDOS AGUILERA LEON': 40, 'NOBOA PONTON ALVARO FERNANDO': 7, 'NEIRA MENENDEZ ANTONIO XAVIER': 6, 'ALARCON COSTTA  CESAR AUGUSTO': 11, 'JUEZ ABUCHAKRA IVONNE LEYLA': 201, 'BUCARAM ORTIZ JACOBO': 10, 'GUTIERREZ BORBUA LUCIO EDWIN': 202}

{'BORJA CEVALLOS RODRIGO': 12,
 'VELAZQUEZ HERRERA JACINTO': 22,
 'VARGAS GUATATUCA CARLOS ANTONIO': 28,
 'HURTADO LARREA  OSVALDO': 24,
 'ROLDOS AGUILERA LEON': 40,
 'NOBOA PONTON ALVARO FERNANDO': 7,
 'NEIRA MENENDEZ ANTONIO XAVIER': 6,
 'ALARCON COSTTA  CESAR AUGUSTO': 11,
 'JUEZ ABUCHAKRA IVONNE LEYLA': 201,
 'BUCARAM ORTIZ JACOBO': 10,
 'GUTIERREZ BORBUA LUCIO EDWIN': 202}

In [57]:
# to do Crear funcion para crear nuevas columnas con el apellido del candidato y los votos por sexo
# pero esta version ya es funcional

# 
#itera sobre el diccionario y crea las nuevas columnas
for candidato, codigo in candidatos_dict.items():
    columna_m = f'VC_{candidato.split()[0]}_M'
    columna_f = f'VC_{candidato.split()[0]}_F'
    cne2002agFV1[columna_m]= cne2002agFV1.loc[cne2002agFV1['CANDIDATO_NOMBRE'] == candidato, 'VOTOS_CANDIDATO_M']
    cne2002agFV1[columna_f]= cne2002agFV1.loc[cne2002agFV1['CANDIDATO_NOMBRE'] == candidato, 'VOTOS_CANDIDATO_F']
    cne2002agFV1[columna_f]= cne2002agFV1[columna_f].fillna(0)
    cne2002agFV1[columna_m]= cne2002agFV1[columna_m].fillna(0)

#Verifica los cambios
cne2002agFV1

,AÑO,VUELTA,CANTON_CODIGO,OP_CODIGO,NUMERO_DE_ACTAS,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,VOTOS_CANDIDATO_M,...,VC_NEIRA_M,VC_NEIRA_F,VC_ALARCON_M,VC_ALARCON_F,VC_JUEZ_M,VC_JUEZ_F,VC_BUCARAM_M,VC_BUCARAM_F,VC_GUTIERREZ_M,VC_GUTIERREZ_F
0,2002,1,5,201,185,1260.0,1326.0,470.0,619.0,231.0,...,0.0,0.0,0.0,0.0,231.0,402.0,0.0,0.0,0.0,0.0
1,2002,1,5,202,185,1260.0,1326.0,470.0,619.0,3580.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3580.0,3614.0
2,2002,1,5,6,185,1260.0,1326.0,470.0,619.0,773.0,...,773.0,810.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2002,1,5,7,185,1260.0,1326.0,470.0,619.0,5924.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2002,1,5,10,185,1260.0,1326.0,470.0,619.0,978.0,...,0.0,0.0,0.0,0.0,0.0,0.0,978.0,826.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2382,2002,1,995,12,19,97.0,98.0,94.0,100.0,406.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2383,2002,1,995,22,19,97.0,98.0,94.0,100.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2384,2002,1,995,24,19,97.0,98.0,94.0,100.0,14.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2385,2002,1,995,28,19,97.0,98.0,94.0,100.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2386,2002,1,995,40,19,97.0,98.0,94.0,100.0,134.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [58]:
cne2002agFV1.dtypes

AÑO                    int64
VUELTA                 int64
CANTON_CODIGO          int32
OP_CODIGO              int32
NUMERO_DE_ACTAS        int32
VOTOS_NULOS_M        float64
VOTOS_NULOS_F        float64
VOTOS_BLANCOS_M      float64
VOTOS_BLANCOS_F      float64
VOTOS_CANDIDATO_M    float64
VOTOS_CANDIDATO_F    float64
CANDIDATO_NOMBRE      object
CANDIDATO_EDAD         int32
CANDIDATO_SEXO        object
OP_CODIGO              int32
ELECTORES_M          float64
ELECTORAS_F          float64
OP_TIPO               object
OP_AMBITO             object
OP_NOMBRE             object
OP_SIGLAS             object
VC_BORJA_M           float64
VC_BORJA_F           float64
VC_VELAZQUEZ_M       float64
VC_VELAZQUEZ_F       float64
VC_VARGAS_M          float64
VC_VARGAS_F          float64
VC_HURTADO_M         float64
VC_HURTADO_F         float64
VC_ROLDOS_M          float64
VC_ROLDOS_F          float64
VC_NOBOA_M           float64
VC_NOBOA_F           float64
VC_NEIRA_M           float64
VC_NEIRA_F           float64
VC_ALARCON_M         float64
VC_ALARCON_F         float64
VC_JUEZ_M            float64
VC_JUEZ_F            float64
VC_BUCARAM_M         float64
VC_BUCARAM_F         float64
VC_GUTIERREZ_M       float64
VC_GUTIERREZ_F       float64
dtype: object

In [59]:
cne2002agFV1 = cne2002agFV1.drop("VOTOS_CANDIDATO_F", axis=1)
cne2002agFV1 = cne2002agFV1.drop("VOTOS_CANDIDATO_M", axis=1)

In [60]:
cne2002agFV1

,AÑO,VUELTA,CANTON_CODIGO,OP_CODIGO,NUMERO_DE_ACTAS,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,CANDIDATO_NOMBRE,...,VC_NEIRA_M,VC_NEIRA_F,VC_ALARCON_M,VC_ALARCON_F,VC_JUEZ_M,VC_JUEZ_F,VC_BUCARAM_M,VC_BUCARAM_F,VC_GUTIERREZ_M,VC_GUTIERREZ_F
0,2002,1,5,201,185,1260.0,1326.0,470.0,619.0,JUEZ ABUCHAKRA IVONNE LEYLA,...,0.0,0.0,0.0,0.0,231.0,402.0,0.0,0.0,0.0,0.0
1,2002,1,5,202,185,1260.0,1326.0,470.0,619.0,GUTIERREZ BORBUA LUCIO EDWIN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3580.0,3614.0
2,2002,1,5,6,185,1260.0,1326.0,470.0,619.0,NEIRA MENENDEZ ANTONIO XAVIER,...,773.0,810.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2002,1,5,7,185,1260.0,1326.0,470.0,619.0,NOBOA PONTON ALVARO FERNANDO,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2002,1,5,10,185,1260.0,1326.0,470.0,619.0,BUCARAM ORTIZ JACOBO,...,0.0,0.0,0.0,0.0,0.0,0.0,978.0,826.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2382,2002,1,995,12,19,97.0,98.0,94.0,100.0,BORJA CEVALLOS RODRIGO,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2383,2002,1,995,22,19,97.0,98.0,94.0,100.0,VELAZQUEZ HERRERA JACINTO,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2384,2002,1,995,24,19,97.0,98.0,94.0,100.0,HURTADO LARREA OSVALDO,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2385,2002,1,995,28,19,97.0,98.0,94.0,100.0,VARGAS GUATATUCA CARLOS ANTONIO,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2386,2002,1,995,40,19,97.0,98.0,94.0,100.0,ROLDOS AGUILERA LEON,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [61]:

columnas_votos = [f'VC_{candidato.split()[0]}_M' for candidato in candidatos_dict.keys()] + [f'VC_{candidato.split()[0]}_F' for candidato in candidatos_dict.keys()]
columnas_votos

['VC_BORJA_M',
 'VC_VELAZQUEZ_M',
 'VC_VARGAS_M',
 'VC_HURTADO_M',
 'VC_ROLDOS_M',
 'VC_NOBOA_M',
 'VC_NEIRA_M',
 'VC_ALARCON_M',
 'VC_JUEZ_M',
 'VC_BUCARAM_M',
 'VC_GUTIERREZ_M',
 'VC_BORJA_F',
 'VC_VELAZQUEZ_F',
 'VC_VARGAS_F',
 'VC_HURTADO_F',
 'VC_ROLDOS_F',
 'VC_NOBOA_F',
 'VC_NEIRA_F',
 'VC_ALARCON_F',
 'VC_JUEZ_F',
 'VC_BUCARAM_F',
 'VC_GUTIERREZ_F']

In [62]:
#Agregado por CANTON
cne2002agFV1CANTON= cne2002agFV1.groupby(['CANTON_CODIGO']).agg({
    'VOTOS_NULOS_M':'mean',
    'VOTOS_NULOS_F':'mean',
    'VOTOS_BLANCOS_M': 'mean',
    'VOTOS_BLANCOS_F': 'mean',
**{columna: 'sum' for columna in columnas_votos}

}).reset_index()

cne2002agFV1CANTON

,CANTON_CODIGO,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,VC_BORJA_M,VC_VELAZQUEZ_M,VC_VARGAS_M,VC_HURTADO_M,VC_ROLDOS_M,...,VC_VELAZQUEZ_F,VC_VARGAS_F,VC_HURTADO_F,VC_ROLDOS_F,VC_NOBOA_F,VC_NEIRA_F,VC_ALARCON_F,VC_JUEZ_F,VC_BUCARAM_F,VC_GUTIERREZ_F
0,5,1260.0,1326.0,470.0,619.0,3566.0,238.0,76.0,271.0,1466.0,...,280.0,56.0,303.0,1807.0,6090.0,810.0,336.0,402.0,826.0,3614.0
1,10,681.0,648.0,224.0,306.0,1868.0,59.0,31.0,93.0,547.0,...,55.0,28.0,87.0,659.0,1805.0,317.0,75.0,131.0,584.0,1450.0
2,15,313.0,389.0,102.0,146.0,662.0,31.0,17.0,45.0,337.0,...,25.0,10.0,39.0,360.0,754.0,190.0,24.0,84.0,327.0,816.0
3,20,326.0,395.0,179.0,176.0,600.0,38.0,8.0,24.0,220.0,...,23.0,11.0,24.0,284.0,426.0,84.0,11.0,40.0,362.0,469.0
4,25,350.0,377.0,206.0,219.0,818.0,25.0,15.0,66.0,204.0,...,28.0,10.0,50.0,251.0,749.0,119.0,26.0,87.0,191.0,510.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,980,63.0,117.0,156.0,128.0,37.0,3.0,8.0,7.0,158.0,...,1.0,2.0,10.0,196.0,155.0,78.0,3.0,17.0,152.0,471.0
213,985,153.0,143.0,100.0,107.0,164.0,27.0,7.0,10.0,108.0,...,11.0,4.0,4.0,127.0,276.0,370.0,7.0,45.0,213.0,279.0
214,986,175.0,242.0,262.0,185.0,43.0,4.0,4.0,1.0,106.0,...,5.0,1.0,3.0,156.0,407.0,426.0,2.0,20.0,307.0,54.0
215,990,62.0,100.0,44.0,42.0,224.0,8.0,4.0,3.0,44.0,...,4.0,2.0,4.0,50.0,93.0,34.0,1.0,4.0,38.0,131.0
216,995,97.0,98.0,94.0,100.0,406.0,12.0,7.0,14.0,134.0,...,6.0,4.0,24.0,144.0,489.0,50.0,24.0,50.0,193.0,321.0

In [63]:
cne2002agFV1CANTON['CANTON_CODIGO'] = cne2002agFV1CANTON['CANTON_CODIGO'].astype(int)
cne2002RPA['CANTON_CODIGO'] = cne2002RPA['CANTON_CODIGO'].astype(int)

In [64]:
#Match llave primaria para unir a los electores por canton

cne2002agFV1CANTON['ELECTORES_M'] = cne2002agFV1CANTON['CANTON_CODIGO'].map(cne2002RPA.set_index('CANTON_CODIGO')['ELECTORES_M'])
cne2002agFV1CANTON['ELECTORAS_F'] = cne2002agFV1CANTON['CANTON_CODIGO'].map(cne2002RPA.set_index('CANTON_CODIGO')['ELECTORAS_F'])

cne2002agFV1CANTON

,CANTON_CODIGO,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,VC_BORJA_M,VC_VELAZQUEZ_M,VC_VARGAS_M,VC_HURTADO_M,VC_ROLDOS_M,...,VC_HURTADO_F,VC_ROLDOS_F,VC_NOBOA_F,VC_NEIRA_F,VC_ALARCON_F,VC_JUEZ_F,VC_BUCARAM_F,VC_GUTIERREZ_F,ELECTORES_M,ELECTORAS_F
0,5,1260.0,1326.0,470.0,619.0,3566.0,238.0,76.0,271.0,1466.0,...,303.0,1807.0,6090.0,810.0,336.0,402.0,826.0,3614.0,26308.0,26757.0
1,10,681.0,648.0,224.0,306.0,1868.0,59.0,31.0,93.0,547.0,...,87.0,659.0,1805.0,317.0,75.0,131.0,584.0,1450.0,10646.0,11151.0
2,15,313.0,389.0,102.0,146.0,662.0,31.0,17.0,45.0,337.0,...,39.0,360.0,754.0,190.0,24.0,84.0,327.0,816.0,5195.0,5475.0
3,20,326.0,395.0,179.0,176.0,600.0,38.0,8.0,24.0,220.0,...,24.0,284.0,426.0,84.0,11.0,40.0,362.0,469.0,4530.0,4469.0
4,25,350.0,377.0,206.0,219.0,818.0,25.0,15.0,66.0,204.0,...,50.0,251.0,749.0,119.0,26.0,87.0,191.0,510.0,5210.0,5034.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,980,63.0,117.0,156.0,128.0,37.0,3.0,8.0,7.0,158.0,...,10.0,196.0,155.0,78.0,3.0,17.0,152.0,471.0,2489.0,2270.0
213,985,153.0,143.0,100.0,107.0,164.0,27.0,7.0,10.0,108.0,...,4.0,127.0,276.0,370.0,7.0,45.0,213.0,279.0,3076.0,2789.0
214,986,175.0,242.0,262.0,185.0,43.0,4.0,4.0,1.0,106.0,...,3.0,156.0,407.0,426.0,2.0,20.0,307.0,54.0,2424.0,2156.0
215,990,62.0,100.0,44.0,42.0,224.0,8.0,4.0,3.0,44.0,...,4.0,50.0,93.0,34.0,1.0,4.0,38.0,131.0,1104.0,1192.0
216,995,97.0,98.0,94.0,100.0,406.0,12.0,7.0,14.0,134.0,...,24.0,144.0,489.0,50.0,24.0,50.0,193.0,321.0,2603.0,2507.0

In [65]:
#Creación de votos válidos
#Calcula la columna "VOTOS VALIDOS"
cne2002agFV1CANTON["VOTOS VALIDOS"] = cne2002agFV1CANTON[columnas_votos].sum(axis=1)
cne2002agFV1CANTON

,CANTON_CODIGO,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,VC_BORJA_M,VC_VELAZQUEZ_M,VC_VARGAS_M,VC_HURTADO_M,VC_ROLDOS_M,...,VC_ROLDOS_F,VC_NOBOA_F,VC_NEIRA_F,VC_ALARCON_F,VC_JUEZ_F,VC_BUCARAM_F,VC_GUTIERREZ_F,ELECTORES_M,ELECTORAS_F,VOTOS VALIDOS
0,5,1260.0,1326.0,470.0,619.0,3566.0,238.0,76.0,271.0,1466.0,...,1807.0,6090.0,810.0,336.0,402.0,826.0,3614.0,26308.0,26757.0,35311.0
1,10,681.0,648.0,224.0,306.0,1868.0,59.0,31.0,93.0,547.0,...,659.0,1805.0,317.0,75.0,131.0,584.0,1450.0,10646.0,11151.0,14068.0
2,15,313.0,389.0,102.0,146.0,662.0,31.0,17.0,45.0,337.0,...,360.0,754.0,190.0,24.0,84.0,327.0,816.0,5195.0,5475.0,6592.0
3,20,326.0,395.0,179.0,176.0,600.0,38.0,8.0,24.0,220.0,...,284.0,426.0,84.0,11.0,40.0,362.0,469.0,4530.0,4469.0,4827.0
4,25,350.0,377.0,206.0,219.0,818.0,25.0,15.0,66.0,204.0,...,251.0,749.0,119.0,26.0,87.0,191.0,510.0,5210.0,5034.0,5854.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,980,63.0,117.0,156.0,128.0,37.0,3.0,8.0,7.0,158.0,...,196.0,155.0,78.0,3.0,17.0,152.0,471.0,2489.0,2270.0,2266.0
213,985,153.0,143.0,100.0,107.0,164.0,27.0,7.0,10.0,108.0,...,127.0,276.0,370.0,7.0,45.0,213.0,279.0,3076.0,2789.0,3186.0
214,986,175.0,242.0,262.0,185.0,43.0,4.0,4.0,1.0,106.0,...,156.0,407.0,426.0,2.0,20.0,307.0,54.0,2424.0,2156.0,3018.0
215,990,62.0,100.0,44.0,42.0,224.0,8.0,4.0,3.0,44.0,...,50.0,93.0,34.0,1.0,4.0,38.0,131.0,1104.0,1192.0,1166.0
216,995,97.0,98.0,94.0,100.0,406.0,12.0,7.0,14.0,134.0,...,144.0,489.0,50.0,24.0,50.0,193.0,321.0,2603.0,2507.0,3533.0

In [66]:
#Define la lista de columnas de votos inválidos
columnas_votos_invalidos = ["VOTOS_NULOS_M", "VOTOS_NULOS_F", "VOTOS_BLANCOS_M", "VOTOS_BLANCOS_F"]

# Calcula la columna "VOTOS_INVALIDOS"
cne2002agFV1CANTON["VOTOS_INVALIDOS"] = cne2002agFV1CANTON[columnas_votos_invalidos].sum(axis=1)

### Match de cantones

In [67]:
#Match de cantones

cne2002agFV1CANTON['CANTON_CODIGO'] = cne2002agFV1CANTON['CANTON_CODIGO'].astype(int)
cne2002RPA['CANTON_CODIGO'] = cne2002RPA['CANTON_CODIGO'].astype(int)

In [68]:
cantones_2002= pd.read_spss("../raw/diccionarios/cantones_2002.sav")

In [69]:
cantones_2002

     PROVINCIA_CODIGO PROVINCIA_NOMBRE  CANTON_CODIGO        CANTON_NOMBRE
0                 1.0            AZUAY          260.0               CUENCA
1                 1.0            AZUAY          265.0             GUALACEO
2                 1.0            AZUAY          270.0                GIRON
3                 1.0            AZUAY          275.0                PAUTE
4                 1.0            AZUAY          280.0               SIGSIG
..                ...              ...            ...                  ...
212              21.0        SUCUMBIOS          865.0      GONZALO PIZARRO
213              22.0         ORELLANA          630.0             AGUARICO
214              22.0         ORELLANA          645.0      FCO.DE ORELLANA
215              22.0         ORELLANA          725.0  JOYA DE LOS SAGCHAS
216              22.0         ORELLANA          935.0               LORETO

[217 rows x 4 columns]

In [70]:
#cne2002agFV1CANTON['CANTON_NOMBRE'] = cne2002agFV1CANTON['CANTON_CODIGO'].map(cantones_2002.set_index('CANTON_CODIGO')['CANTON_NOMBRE'])
cne2002agFV1CANTON['CANTON_NOMBRE'] = cne2002agFV1CANTON['CANTON_CODIGO'].map(cantones_2002.set_index('CANTON_CODIGO')['CANTON_NOMBRE'])
cne2002agFV1CANTON['PROVINCIA_NOMBRE'] = cne2002agFV1CANTON['CANTON_CODIGO'].map(cantones_2002.set_index('CANTON_CODIGO')['PROVINCIA_NOMBRE'])
cne2002agFV1CANTON

,CANTON_CODIGO,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,VC_BORJA_M,VC_VELAZQUEZ_M,VC_VARGAS_M,VC_HURTADO_M,VC_ROLDOS_M,...,VC_ALARCON_F,VC_JUEZ_F,VC_BUCARAM_F,VC_GUTIERREZ_F,ELECTORES_M,ELECTORAS_F,VOTOS VALIDOS,VOTOS_INVALIDOS,CANTON_NOMBRE,PROVINCIA_NOMBRE
0,5,1260.0,1326.0,470.0,619.0,3566.0,238.0,76.0,271.0,1466.0,...,336.0,402.0,826.0,3614.0,26308.0,26757.0,35311.0,3675.0,TULCAN,CARCHI
1,10,681.0,648.0,224.0,306.0,1868.0,59.0,31.0,93.0,547.0,...,75.0,131.0,584.0,1450.0,10646.0,11151.0,14068.0,1859.0,MONTUFAR,CARCHI
2,15,313.0,389.0,102.0,146.0,662.0,31.0,17.0,45.0,337.0,...,24.0,84.0,327.0,816.0,5195.0,5475.0,6592.0,950.0,ESPEJO,CARCHI
3,20,326.0,395.0,179.0,176.0,600.0,38.0,8.0,24.0,220.0,...,11.0,40.0,362.0,469.0,4530.0,4469.0,4827.0,1076.0,MIRA,CARCHI
4,25,350.0,377.0,206.0,219.0,818.0,25.0,15.0,66.0,204.0,...,26.0,87.0,191.0,510.0,5210.0,5034.0,5854.0,1152.0,BOLIVAR,CARCHI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,980,63.0,117.0,156.0,128.0,37.0,3.0,8.0,7.0,158.0,...,3.0,17.0,152.0,471.0,2489.0,2270.0,2266.0,464.0,CENTINELA DEL CONDOR,ZAMORA CHINCHIPE
213,985,153.0,143.0,100.0,107.0,164.0,27.0,7.0,10.0,108.0,...,7.0,45.0,213.0,279.0,3076.0,2789.0,3186.0,503.0,GRAL. A. ELIZALDE,GUAYAS
214,986,175.0,242.0,262.0,185.0,43.0,4.0,4.0,1.0,106.0,...,2.0,20.0,307.0,54.0,2424.0,2156.0,3018.0,864.0,ISIDRO AYORA,GUAYAS
215,990,62.0,100.0,44.0,42.0,224.0,8.0,4.0,3.0,44.0,...,1.0,4.0,38.0,131.0,1104.0,1192.0,1166.0,248.0,GUACHAPALA,AZUAY
216,995,97.0,98.0,94.0,100.0,406.0,12.0,7.0,14.0,134.0,...,24.0,50.0,193.0,321.0,2603.0,2507.0,3533.0,389.0,SAN PEDRO DE HUACA,CARCHI

In [71]:
# Agregar la columna "AÑO" con valor 2004 al principio del dataframe
cne2002agFV1CANTON.insert(0, "AÑO", 2002)

# Agregar la columna "VUELTA" con valor 2 al principio del dataframe
cne2002agFV1CANTON.insert(1, "VUELTA", 1)

cne2002agFV1CANTON

,AÑO,VUELTA,CANTON_CODIGO,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,VC_BORJA_M,VC_VELAZQUEZ_M,VC_VARGAS_M,...,VC_ALARCON_F,VC_JUEZ_F,VC_BUCARAM_F,VC_GUTIERREZ_F,ELECTORES_M,ELECTORAS_F,VOTOS VALIDOS,VOTOS_INVALIDOS,CANTON_NOMBRE,PROVINCIA_NOMBRE
0,2002,1,5,1260.0,1326.0,470.0,619.0,3566.0,238.0,76.0,...,336.0,402.0,826.0,3614.0,26308.0,26757.0,35311.0,3675.0,TULCAN,CARCHI
1,2002,1,10,681.0,648.0,224.0,306.0,1868.0,59.0,31.0,...,75.0,131.0,584.0,1450.0,10646.0,11151.0,14068.0,1859.0,MONTUFAR,CARCHI
2,2002,1,15,313.0,389.0,102.0,146.0,662.0,31.0,17.0,...,24.0,84.0,327.0,816.0,5195.0,5475.0,6592.0,950.0,ESPEJO,CARCHI
3,2002,1,20,326.0,395.0,179.0,176.0,600.0,38.0,8.0,...,11.0,40.0,362.0,469.0,4530.0,4469.0,4827.0,1076.0,MIRA,CARCHI
4,2002,1,25,350.0,377.0,206.0,219.0,818.0,25.0,15.0,...,26.0,87.0,191.0,510.0,5210.0,5034.0,5854.0,1152.0,BOLIVAR,CARCHI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,2002,1,980,63.0,117.0,156.0,128.0,37.0,3.0,8.0,...,3.0,17.0,152.0,471.0,2489.0,2270.0,2266.0,464.0,CENTINELA DEL CONDOR,ZAMORA CHINCHIPE
213,2002,1,985,153.0,143.0,100.0,107.0,164.0,27.0,7.0,...,7.0,45.0,213.0,279.0,3076.0,2789.0,3186.0,503.0,GRAL. A. ELIZALDE,GUAYAS
214,2002,1,986,175.0,242.0,262.0,185.0,43.0,4.0,4.0,...,2.0,20.0,307.0,54.0,2424.0,2156.0,3018.0,864.0,ISIDRO AYORA,GUAYAS
215,2002,1,990,62.0,100.0,44.0,42.0,224.0,8.0,4.0,...,1.0,4.0,38.0,131.0,1104.0,1192.0,1166.0,248.0,GUACHAPALA,AZUAY
216,2002,1,995,97.0,98.0,94.0,100.0,406.0,12.0,7.0,...,24.0,50.0,193.0,321.0,2603.0,2507.0,3533.0,389.0,SAN PEDRO DE HUACA,CARCHI

In [72]:
cne2002agFV1CANTON.to_csv('../bases_limpias/cne2002agFV1CANTON.csv')

# To Do
- [x] Cargar y Preparar Datos
- [x] Mapeo de Códigos de Provincia
- [ ] Mapeo de Códigos de Cantón
- [ ] Mapeo de Códigos de Parroquia
- [x] Revision de electores, sufragantes, votos inválidos, votos válidos
- [x] Pasar de codigo de Candidato a codigo de organización política
- [masomenos] Crear funcion para crear nuevas columnas con el apellido del candidato y los votos por sexo
- [ ] Codificar el nulo y el blanco como un candidato más

In [73]:
#creacion funciones para automatizar
def crear_diccionario_candidatos(df):
    candidatos_dict = dict(zip(df['CANDIDATO_NOMBRE'], df['OP_CODIGO']))
    return candidatos_dict
    
    
    
def agregar_columnas_votos(df, candidatos_dict):
    for candidato in candidatos_dict.keys():
        columna_m = f'VC_{candidato.split()[0]}_M'
        columna_f = f'VC_{candidato.split()[0]}_F'
        df[columna_m]= df.loc[df['CANDIDATO_NOMBRE'] == candidato, 'VOTOS_CANDIDATO_M']
        df[columna_f]= df.loc[df['CANDIDATO_NOMBRE'] == candidato, 'VOTOS_CANDIDATO_F']
        df[columna_f]= df[columna_f].fillna(0)
        df[columna_m]= df[columna_m].fillna(0)
    return df