# Análisis de Elecciones Presidenciales 2006 de Ecuador

Descripción

Campos de la base resultante:
La base que necesitamos construir deberá tener las siguientes columnas:
- Año
- Vuelta
- Parroquia
- Cantón
- Provincia
- Electores
- Sufragantes
- Votos nulos
- Votos blancos
- Votos inválidos
- Votos válidos
- Candidato
- Organización política
- Votos femeninos por el candidato
- Votos masculinos por el candidato
- Votos totales por el candidato
- Estado del candidato (ganó o no ganó)

### Librerias

In [1]:
# Se instalan las librerías necesarias

# Para leer archivos.sav
! pip install pyreadstat           
 # Para trabajar con dataframes
! pip install pandas              
# Para trabajar con matrices
! pip install numpy                
# Para hacer un reporte de los datos
! pip install pandas-profiling

Requirement already satisfied: pyreadstat in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (1.2.2)
Requirement already satisfied: pandas>=1.2.0 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from pyreadstat) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\saidm\appdata\roaming\python\python310\site-packages (from pandas>=1.2.0->pyreadstat) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from pandas>=1.2.0->pyreadstat) (2023.2)
Requirement already satisfied: numpy>=1.21.0 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from pandas>=1.2.0->pyreadstat) (1.23.5)
Requirement already satisfied: six>=1.5 in c:\users\saidm\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.1->pandas>=1.2.0->pyreadstat) (1.16.0)
Requirement already satisfied: pandas in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\saidm\appdata\roaming\python\python310\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2023.2)
Requirement already satisfied: numpy>=1.21.0 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in c:\users\saidm\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Requirement already satisfied: numpy in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (1.23.5)
Requirement already satisfied: pandas-profiling in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (3.6.6)
Requirement already satisfied: ydata-profiling in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from pandas-profiling) (4.3.1)
Requirement already satisfied: scipy<1.11,>=1.4.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (1.10.1)
Requirement already satisfied: pandas!=1.4.0,<2.1,>1.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (1.5.3)
Requirement already satisfied: matplotlib<4,>=3.2 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (3.7.1)
Requirement already satisfied: pydantic<2,>=1.8.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (1.10.10)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (6.0)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (3.1.2)
Requirement already satisfied: visions[type_image_path]==0.7.5 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (0.7.5)
Requirement already satisfied: numpy<1.24,>=1.16.0 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (1.23.5)
Requirement already satisfied: htmlmin==0.1.12 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (0.1.12)
Requirement already satisfied: phik<0.13,>=0.11.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (0.12.3)
Requirement already satisfied: requests<3,>=2.24.0 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (2.31.0)
Requirement already satisfied: tqdm<5,>=4.48.2 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (4.65.0)
Requirement already satisfied: seaborn<0.13,>=0.10.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (0.12.2)
Requirement already satisfied: multimethod<2,>=1.4 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (1.9.1)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (0.14.0)
Requirement already satisfied: typeguard<3,>=2.13.2 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (2.13.3)
Requirement already satisfied: imagehash==4.3.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (4.3.1)
Requirement already satisfied: wordcloud>=1.9.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (1.9.2)
Requirement already satisfied: dacite>=1.8 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from ydata-profiling->pandas-profiling) (1.8.1)
Requirement already satisfied: PyWavelets in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from imagehash==4.3.1->ydata-profiling->pandas-profiling) (1.4.1)
Requirement already satisfied: pillow in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from imagehash==4.3.1->ydata-profiling->pandas-profiling) (9.4.0)
Requirement already satisfied: attrs>=19.3.0 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from visions[type_image_path]==0.7.5->ydata-profiling->pandas-profiling) (23.1.0)
Requirement already satisfied: networkx>=2.4 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from visions[type_image_path]==0.7.5->ydata-profiling->pandas-profiling) (3.0)
Requirement already satisfied: tangled-up-in-unicode>=0.0.4 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from visions[type_image_path]==0.7.5->ydata-profiling->pandas-profiling) (0.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling->pandas-profiling) (2.1.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (1.0.7)
Requirement already satisfied: cycler>=0.10 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (4.39.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\saidm\appdata\roaming\python\python310\site-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (23.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\saidm\appdata\roaming\python\python310\site-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from pandas!=1.4.0,<2.1,>1.1->ydata-profiling->pandas-profiling) (2023.2)
Requirement already satisfied: joblib>=0.14.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from phik<0.13,>=0.11.1->ydata-profiling->pandas-profiling) (1.3.1)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from pydantic<2,>=1.8.1->ydata-profiling->pandas-profiling) (4.7.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (2.0.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (2023.5.7)
Requirement already satisfied: patsy>=0.5.2 in c:\users\saidm\appdata\local\programs\python\python310\lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling->pandas-profiling) (0.5.3)
Requirement already satisfied: colorama in c:\users\saidm\appdata\roaming\python\python310\site-packages (from tqdm<5,>=4.48.2->ydata-profiling->pandas-profiling) (0.4.6)
Requirement already satisfied: six in c:\users\saidm\appdata\roaming\python\python310\site-packages (from patsy>=0.5.2->statsmodels<1,>=0.13.2->ydata-profiling->pandas-profiling) (1.16.0)

In [2]:
# Se importan las librerías necesarias

import pandas as pd
import numpy as np
import pyreadstat as py
from pandas_profiling import ProfileReport
import matplotlib.pyplot as plt

C:\Users\saidm\AppData\Local\Temp\ipykernel_22376\1559778840.py:6: DeprecationWarning: `import pandas_profiling` is going to be deprecated by April 1st. Please use `import ydata_profiling` instead.
  from pandas_profiling import ProfileReport

### Limpieza y Preparación de Datos de la Base de Datos de la Segunda Vuelta
La base es"resultados_presidenciales_2002.csv"

In [3]:
provincias = pd.read_spss("../raw//diccionarios/provincias 2006 (1).sav")

In [4]:
provincias

    PROVINCIA_CODIGO  PROVINCIA_NOMBRE
0                0.0           ECUADOR
1                1.0             AZUAY
2                2.0           BOLIVAR
3                3.0             CANAR
4                4.0            CARCHI
5                5.0          COTOPAXI
6                6.0        CHIMBORAZO
7                7.0            EL ORO
8                8.0        ESMERALDAS
9                9.0            GUAYAS
10              10.0          IMBABURA
11              11.0              LOJA
12              12.0          LOS RIOS
13              13.0            MANABI
14              14.0   MORONA SANTIAGO
15              15.0              NAPO
16              16.0           PASTAZA
17              17.0         PICHINCHA
18              18.0        TUNGURAHUA
19              19.0  ZAMORA CHINCHIPE
20              20.0         GALAPAGOS
21              21.0         SUCUMBIOS
22              22.0          ORELLANA
23              25.0     VOTO EXTERIOR

In [5]:
cne2006resultadosV2= pd.read_spss("../raw/resultados/Resultados segunda vuelta a nivel parroquial 2006.sav")

In [6]:
cne2006resultadosV2

,DIGNIDAD_CODIGO,PROVINCIA_CODIGO,CANTON_CODIGO,PARROQUIA_CODIGO,SEXO,NUMERO_DE_ACTAS,VOTOS_EN_BLANCO,VOTOS_NULOS,OP_CODIGO,CANDIDATO_CODIGO,CANDIDATO_VOTOS,CANDIDATO_ESTADO
0,1.0,1.0,556.0,6875.0,MUJERES,10.0,31.0,171.0,5.0,1.000000e+12,584.0,NaN
1,1.0,1.0,556.0,6875.0,HOMBRES,12.0,25.0,170.0,5.0,1.000000e+12,672.0,NaN
2,1.0,1.0,915.0,6435.0,MUJERES,12.0,61.0,330.0,5.0,1.000000e+12,419.0,NaN
3,1.0,1.0,915.0,6435.0,HOMBRES,11.0,22.0,192.0,5.0,1.000000e+12,377.0,NaN
4,1.0,1.0,915.0,1535.0,MUJERES,1.0,5.0,29.0,5.0,1.000000e+12,18.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
4957,1.0,19.0,655.0,1770.0,HOMBRES,2.0,1.0,14.0,72.0,1.000000e+12,192.0,ELECTOS
4958,1.0,19.0,655.0,4010.0,MUJERES,2.0,1.0,7.0,72.0,1.000000e+12,108.0,ELECTOS
4959,1.0,19.0,655.0,4010.0,HOMBRES,2.0,0.0,6.0,72.0,1.000000e+12,114.0,ELECTOS
4960,1.0,19.0,655.0,6305.0,MUJERES,15.0,28.0,184.0,72.0,1.000000e+12,1706.0,ELECTOS
4961,1.0,19.0,655.0,6305.0,HOMBRES,15.0,20.0,145.0,72.0,1.000000e+12,1586.0,ELECTOS

In [7]:
cne2006resultadosV2.dtypes

DIGNIDAD_CODIGO      float64
PROVINCIA_CODIGO     float64
CANTON_CODIGO        float64
PARROQUIA_CODIGO     float64
SEXO                category
NUMERO_DE_ACTAS      float64
VOTOS_EN_BLANCO      float64
VOTOS_NULOS          float64
OP_CODIGO            float64
CANDIDATO_CODIGO     float64
CANDIDATO_VOTOS      float64
CANDIDATO_ESTADO    category
dtype: object

In [8]:
# Cargar el diccionario 'provincias_2002.csv' en un DataFrame
diccionario_provincias = pd.read_spss("../raw//diccionarios/provincias 2006 (1).sav")
#diccionario_provincias.drop(columns=['Unnamed: 0'],inplace=True)
# Convertir el tipo de datos de la columna 'PROVINCIA_CODIGO' a string en el DataFrame 'cne2006resultadosV2'
cne2006resultadosV2['PROVINCIA_CODIGO'] = cne2006resultadosV2['PROVINCIA_CODIGO'].astype(str)

# Limpiar las claves del diccionario 'mapeo_csv' y los valores de la columna 'PROVINCIA_CODIGO'
mapeo_csv = dict(zip(diccionario_provincias['PROVINCIA_CODIGO'].astype(str), diccionario_provincias['PROVINCIA_NOMBRE']))
# Mapear los códigos de provincia del DataFrame 'cne2006resultadosV2' utilizando el diccionario CSV
cne2006resultadosV2['PROVINCIA_CODIGO'] = cne2006resultadosV2['PROVINCIA_CODIGO'].map(mapeo_csv)


#capitalizar todas las palabras de la columna 'PROVINCIA_CODIGO'
cne2006resultadosV2['PROVINCIA_CODIGO'] = cne2006resultadosV2['PROVINCIA_CODIGO'].str.title()
# Cargar el diccionario estandarizado 'provincias.tsv' en un DataFrame
diccionario_estandarizado = pd.read_csv('../diccionarios estandar/provincias.tsv', sep='\t')
# Crear un diccionario de mapeo de código a nombre de provincia del diccionario estandarizado
mapeo_estandarizado = dict(zip(diccionario_estandarizado['provincia'], diccionario_estandarizado['cod_provincia']))

# Mapear los códigos de provincia del DataFrame 'cne2006resultadosV2' utilizando el diccionario estandarizado
cne2006resultadosV2['PROVINCIA_CODIGO'] = cne2006resultadosV2['PROVINCIA_CODIGO'].map(mapeo_estandarizado)

In [9]:
# Imprimir el DataFrame actualizado
cne2006resultadosV2

,DIGNIDAD_CODIGO,PROVINCIA_CODIGO,CANTON_CODIGO,PARROQUIA_CODIGO,SEXO,NUMERO_DE_ACTAS,VOTOS_EN_BLANCO,VOTOS_NULOS,OP_CODIGO,CANDIDATO_CODIGO,CANDIDATO_VOTOS,CANDIDATO_ESTADO
0,1.0,P1,556.0,6875.0,MUJERES,10.0,31.0,171.0,5.0,1.000000e+12,584.0,NaN
1,1.0,P1,556.0,6875.0,HOMBRES,12.0,25.0,170.0,5.0,1.000000e+12,672.0,NaN
2,1.0,P1,915.0,6435.0,MUJERES,12.0,61.0,330.0,5.0,1.000000e+12,419.0,NaN
3,1.0,P1,915.0,6435.0,HOMBRES,11.0,22.0,192.0,5.0,1.000000e+12,377.0,NaN
4,1.0,P1,915.0,1535.0,MUJERES,1.0,5.0,29.0,5.0,1.000000e+12,18.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
4957,1.0,P19,655.0,1770.0,HOMBRES,2.0,1.0,14.0,72.0,1.000000e+12,192.0,ELECTOS
4958,1.0,P19,655.0,4010.0,MUJERES,2.0,1.0,7.0,72.0,1.000000e+12,108.0,ELECTOS
4959,1.0,P19,655.0,4010.0,HOMBRES,2.0,0.0,6.0,72.0,1.000000e+12,114.0,ELECTOS
4960,1.0,P19,655.0,6305.0,MUJERES,15.0,28.0,184.0,72.0,1.000000e+12,1706.0,ELECTOS
4961,1.0,P19,655.0,6305.0,HOMBRES,15.0,20.0,145.0,72.0,1.000000e+12,1586.0,ELECTOS

In [10]:
#Formatear las columnas necesarios como tipo int
cne2006resultadosV2["DIGNIDAD_CODIGO"] = cne2006resultadosV2["DIGNIDAD_CODIGO"].astype(int)
#cne2006resultadosV2["SEXO"] = cne2006resultadosV2["SEXO"].astype(int)
cne2006resultadosV2["NUMERO_DE_ACTAS"] = cne2006resultadosV2["NUMERO_DE_ACTAS"].astype(int)
cne2006resultadosV2["VOTOS_EN_BLANCO"] = cne2006resultadosV2["VOTOS_EN_BLANCO"].astype(int)
cne2006resultadosV2["VOTOS_NULOS"] = cne2006resultadosV2["VOTOS_NULOS"].astype(int)
cne2006resultadosV2["CANDIDATO_VOTOS"] = cne2006resultadosV2["CANDIDATO_VOTOS"].astype(int)

In [11]:
cne2006resultadosV2

,DIGNIDAD_CODIGO,PROVINCIA_CODIGO,CANTON_CODIGO,PARROQUIA_CODIGO,SEXO,NUMERO_DE_ACTAS,VOTOS_EN_BLANCO,VOTOS_NULOS,OP_CODIGO,CANDIDATO_CODIGO,CANDIDATO_VOTOS,CANDIDATO_ESTADO
0,1,P1,556.0,6875.0,MUJERES,10,31,171,5.0,1.000000e+12,584,NaN
1,1,P1,556.0,6875.0,HOMBRES,12,25,170,5.0,1.000000e+12,672,NaN
2,1,P1,915.0,6435.0,MUJERES,12,61,330,5.0,1.000000e+12,419,NaN
3,1,P1,915.0,6435.0,HOMBRES,11,22,192,5.0,1.000000e+12,377,NaN
4,1,P1,915.0,1535.0,MUJERES,1,5,29,5.0,1.000000e+12,18,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
4957,1,P19,655.0,1770.0,HOMBRES,2,1,14,72.0,1.000000e+12,192,ELECTOS
4958,1,P19,655.0,4010.0,MUJERES,2,1,7,72.0,1.000000e+12,108,ELECTOS
4959,1,P19,655.0,4010.0,HOMBRES,2,0,6,72.0,1.000000e+12,114,ELECTOS
4960,1,P19,655.0,6305.0,MUJERES,15,28,184,72.0,1.000000e+12,1706,ELECTOS
4961,1,P19,655.0,6305.0,HOMBRES,15,20,145,72.0,1.000000e+12,1586,ELECTOS

In [12]:
#Esta forma de agrupar produce que hayan 4 entradas por cada provincia. Son por los dos sexos y los dos candidatos

# si se retira "PROVINCIA_CODIGO" del groupby, se obtiene el resultado a nivel nacional
cne2006agV2 = cne2006resultadosV2.groupby(['CANDIDATO_CODIGO', 'SEXO','PROVINCIA_CODIGO']).agg({
    'NUMERO_DE_ACTAS': 'sum',
    'VOTOS_EN_BLANCO': 'sum',
    'VOTOS_NULOS': 'sum',
    'CANDIDATO_VOTOS': 'sum'
}).reset_index()
# Crear una columna que muestre la descripción del SEXO
cne2006agV2['SEXO_DESCRIPCION'] = cne2006agV2['SEXO'].map({1: 'MASCULINO', 2: 'FEMENINO'})
cne2006agV2.drop(columns=['SEXO'],inplace=True)

In [13]:
# Mostrar el DataFrame resultante
cne2006agV2

,CANDIDATO_CODIGO,PROVINCIA_CODIGO,NUMERO_DE_ACTAS,VOTOS_EN_BLANCO,VOTOS_NULOS,CANDIDATO_VOTOS,SEXO_DESCRIPCION
0,1.000000e+12,P1,832,1263,13338,35574,NaN
1,1.000000e+12,P10,464,965,9723,29462,NaN
2,1.000000e+12,P11,546,1063,7006,34829,NaN
3,1.000000e+12,P12,848,2785,19476,82846,NaN
4,1.000000e+12,P13,1638,4753,32751,201252,NaN
...,...,...,...,...,...,...,...
83,1.000000e+12,P5,484,1859,15188,74305,NaN
84,1.000000e+12,P6,599,2729,19060,75136,NaN
85,1.000000e+12,P7,671,1209,12984,85777,NaN
86,1.000000e+12,P8,508,1322,11730,40760,NaN
87,1.000000e+12,P9,5298,7439,94695,342524,NaN

### Limpieza y Preparación de Datos de la Base de Datos de la Primera Vuelta
La base es "RESULTADOS_1V_PARROQUIA_2002 (1).SAV"

In [14]:
cne2006resultadosV1= pd.read_spss("../raw/resultados/Resultados primera vuelta a nivel parroquial 2006.sav")

In [15]:
cne2006resultadosV1

,DIGNIDAD_CODIGO,PROVINCIA_CODIGO,CANTON_CODIGO,PARROQUIA_CODIGO,SEXO,NUMERO_DE_ACTAS,VOTOS_EN_BLANCO,VOTOS_NULOS,OP_CODIGO,OP_VOTOS_EN_PLANCHA,CANDIDATO_CODIGO,CANDIDATO_VOTOS,CANDIDATO_ESTADO
0,1.0,1.0,260.0,285.0,HOMBRES,25.0,191.0,496.0,1.0,0.0,1.000000e+12,12.0,NaN
1,1.0,1.0,260.0,285.0,HOMBRES,25.0,191.0,496.0,4.0,0.0,1.000000e+12,181.0,NaN
2,1.0,1.0,260.0,285.0,HOMBRES,25.0,191.0,496.0,5.0,0.0,1.000000e+12,586.0,NaN
3,1.0,1.0,260.0,285.0,HOMBRES,25.0,191.0,496.0,6.0,0.0,1.000000e+12,34.0,NaN
4,1.0,1.0,260.0,285.0,HOMBRES,25.0,191.0,496.0,8.0,0.0,1.000000e+12,23.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
585740,8.0,22.0,935.0,6455.0,MUJERES,7.0,255.0,302.0,72.0,24.0,8.000000e+12,NaN,ELECTOS
585741,8.0,22.0,935.0,6455.0,MUJERES,7.0,255.0,302.0,72.0,24.0,8.000000e+12,NaN,NaN
585742,8.0,22.0,935.0,6455.0,MUJERES,7.0,255.0,302.0,72.0,24.0,8.000000e+12,NaN,NaN
585743,8.0,22.0,935.0,6455.0,MUJERES,7.0,255.0,302.0,72.0,24.0,8.000000e+12,NaN,NaN
585744,8.0,22.0,935.0,6455.0,MUJERES,7.0,255.0,302.0,72.0,24.0,8.000000e+12,NaN,NaN

In [16]:

# Convertir el tipo de datos de la columna 'PROVINCIA_CODIGO' a string en el DataFrame 'cne2006resultadosV1'
cne2006resultadosV1['PROVINCIA_CODIGO'] = cne2006resultadosV1['PROVINCIA_CODIGO'].astype(str)

# Limpiar las claves del diccionario 'mapeo_csv' y los valores de la columna 'PROVINCIA_CODIGO'
mapeo_csv = dict(zip(diccionario_provincias['PROVINCIA_CODIGO'].astype(str), diccionario_provincias['PROVINCIA_NOMBRE']))

# Mapear los códigos de provincia del DataFrame 'cne2006resultadosV1' utilizando el diccionario CSV
cne2006resultadosV1['PROVINCIA_CODIGO'] = cne2006resultadosV1['PROVINCIA_CODIGO'].map(mapeo_csv)

#capitalizar todas las palabras de la columna 'PROVINCIA_CODIGO'
cne2006resultadosV1['PROVINCIA_CODIGO'] = cne2006resultadosV1['PROVINCIA_CODIGO'].str.title()

# Cargar el diccionario estandarizado 'provincias.tsv' en un DataFrame
diccionario_estandarizado = pd.read_csv('../diccionarios estandar/provincias.tsv', sep='\t')
# Crear un diccionario de mapeo de código a nombre de provincia del diccionario estandarizado
mapeo_estandarizado = dict(zip(diccionario_estandarizado['provincia'], diccionario_estandarizado['cod_provincia']))

# Mapear los códigos de provincia del DataFrame 'cne2006resultadosV1' utilizando el diccionario estandarizado
cne2006resultadosV1['PROVINCIA_CODIGO'] = cne2006resultadosV1['PROVINCIA_CODIGO'].map(mapeo_estandarizado)

In [17]:
cne2006resultadosV1

,DIGNIDAD_CODIGO,PROVINCIA_CODIGO,CANTON_CODIGO,PARROQUIA_CODIGO,SEXO,NUMERO_DE_ACTAS,VOTOS_EN_BLANCO,VOTOS_NULOS,OP_CODIGO,OP_VOTOS_EN_PLANCHA,CANDIDATO_CODIGO,CANDIDATO_VOTOS,CANDIDATO_ESTADO
0,1.0,P1,260.0,285.0,HOMBRES,25.0,191.0,496.0,1.0,0.0,1.000000e+12,12.0,NaN
1,1.0,P1,260.0,285.0,HOMBRES,25.0,191.0,496.0,4.0,0.0,1.000000e+12,181.0,NaN
2,1.0,P1,260.0,285.0,HOMBRES,25.0,191.0,496.0,5.0,0.0,1.000000e+12,586.0,NaN
3,1.0,P1,260.0,285.0,HOMBRES,25.0,191.0,496.0,6.0,0.0,1.000000e+12,34.0,NaN
4,1.0,P1,260.0,285.0,HOMBRES,25.0,191.0,496.0,8.0,0.0,1.000000e+12,23.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
585740,8.0,P22,935.0,6455.0,MUJERES,7.0,255.0,302.0,72.0,24.0,8.000000e+12,NaN,ELECTOS
585741,8.0,P22,935.0,6455.0,MUJERES,7.0,255.0,302.0,72.0,24.0,8.000000e+12,NaN,NaN
585742,8.0,P22,935.0,6455.0,MUJERES,7.0,255.0,302.0,72.0,24.0,8.000000e+12,NaN,NaN
585743,8.0,P22,935.0,6455.0,MUJERES,7.0,255.0,302.0,72.0,24.0,8.000000e+12,NaN,NaN
585744,8.0,P22,935.0,6455.0,MUJERES,7.0,255.0,302.0,72.0,24.0,8.000000e+12,NaN,NaN

In [18]:
cne2006resultadosV1["DIGNIDAD_CODIGO"] = cne2006resultadosV1["DIGNIDAD_CODIGO"].astype(int)
#cne2006resultadosV1["SEXO"] = cne2006resultadosV1["SEXO"].astype(int)
cne2006resultadosV1["NUMERO_DE_ACTAS"] = cne2006resultadosV1["NUMERO_DE_ACTAS"].astype(int)
cne2006resultadosV1["VOTOS_EN_BLANCO"] = cne2006resultadosV1["VOTOS_EN_BLANCO"].astype(int)
cne2006resultadosV1["VOTOS_NULOS"] = cne2006resultadosV1["VOTOS_NULOS"].astype(int)
cne2006resultadosV1["CANDIDATO_VOTOS"] = cne2006resultadosV1["CANDIDATO_VOTOS"].fillna(0)
cne2006resultadosV1["CANDIDATO_VOTOS"] = cne2006resultadosV1["CANDIDATO_VOTOS"].astype(int)

#filtrar por dignidad igual a 1
cne2006resultadosV1=cne2006resultadosV1[cne2006resultadosV1['DIGNIDAD_CODIGO']==1.0]

In [19]:
cne2006resultadosV1

,DIGNIDAD_CODIGO,PROVINCIA_CODIGO,CANTON_CODIGO,PARROQUIA_CODIGO,SEXO,NUMERO_DE_ACTAS,VOTOS_EN_BLANCO,VOTOS_NULOS,OP_CODIGO,OP_VOTOS_EN_PLANCHA,CANDIDATO_CODIGO,CANDIDATO_VOTOS,CANDIDATO_ESTADO
0,1,P1,260.0,285.0,HOMBRES,25,191,496,1.0,0.0,1.000000e+12,12,NaN
1,1,P1,260.0,285.0,HOMBRES,25,191,496,4.0,0.0,1.000000e+12,181,NaN
2,1,P1,260.0,285.0,HOMBRES,25,191,496,5.0,0.0,1.000000e+12,586,NaN
3,1,P1,260.0,285.0,HOMBRES,25,191,496,6.0,0.0,1.000000e+12,34,NaN
4,1,P1,260.0,285.0,HOMBRES,25,191,496,8.0,0.0,1.000000e+12,23,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32248,1,NaN,431.0,9065.0,MUJERES,1,0,0,48.0,0.0,1.000000e+12,0,NaN
32249,1,NaN,431.0,9065.0,MUJERES,1,0,0,55.0,0.0,1.000000e+12,0,NaN
32250,1,NaN,431.0,9065.0,MUJERES,1,0,0,62.0,0.0,1.000000e+12,1,NaN
32251,1,NaN,431.0,9065.0,MUJERES,1,0,0,71.0,0.0,1.000000e+12,0,NaN
32252,1,NaN,431.0,9065.0,MUJERES,1,0,0,72.0,0.0,1.000000e+12,0,ELECTOS

In [20]:
cne2006resultadosV1['PROVINCIA_CODIGO'].value_counts()

P11    2574
P17    2496
P13    2366
P9     2314
P1     2288
P7     2106
P8     1742
P18    1638
P6     1586
P14    1508
P10    1274
P5     1196
P12    1027
P3      936
P4      910
P19     884
P21     858
P22     858
P2      754
P15     598
P16     546
P20     208
Name: PROVINCIA_CODIGO, dtype: int64

In [21]:
# agrupación para nivel nacional
cne2006agV1 = cne2006resultadosV1.groupby(['CANTON_CODIGO','CANDIDATO_CODIGO', 'SEXO',]).agg({
    'NUMERO_DE_ACTAS': 'sum',
    'VOTOS_EN_BLANCO': 'sum',
    'VOTOS_NULOS': 'sum',
    'CANDIDATO_VOTOS': 'sum'
}).reset_index()
# Crear una columna que muestre la descripción del SEXO
cne2006agV1=cne2006agV1.rename(columns = {'SEXO':'SEXO_DESCRIPCION'})

cne2006agV1['SEXO'] = cne2006agV1['SEXO_DESCRIPCION'].map({'HOMBRES':1,'MUJERES':2})
#cne2006agV1.drop(columns=['SEXO'],inplace=True)

In [22]:
cne2006agV1

,CANTON_CODIGO,CANDIDATO_CODIGO,SEXO_DESCRIPCION,NUMERO_DE_ACTAS,VOTOS_EN_BLANCO,VOTOS_NULOS,CANDIDATO_VOTOS,SEXO
0,5.0,1.000000e+12,HOMBRES,99,900,2096,683,1
1,5.0,1.000000e+12,MUJERES,101,961,2229,959,2
2,5.0,1.000000e+12,HOMBRES,99,900,2096,45,1
3,5.0,1.000000e+12,MUJERES,101,961,2229,32,2
4,5.0,1.000000e+12,HOMBRES,99,900,2096,948,1
...,...,...,...,...,...,...,...,...
6781,995.0,1.000000e+12,MUJERES,10,99,189,40,2
6782,995.0,1.000000e+12,HOMBRES,10,99,146,705,1
6783,995.0,1.000000e+12,MUJERES,10,99,189,525,2
6784,995.0,1.000000e+12,HOMBRES,10,99,146,5,1
6785,995.0,1.000000e+12,MUJERES,10,99,189,4,2

In [23]:
# Crear columnas separadas
cne2006agV1['VOTOS_NULOS_M'] = cne2006agV1.loc[cne2006agV1['SEXO'] == "1" , 'VOTOS_NULOS']
cne2006agV1['VOTOS_NULOS_F'] = cne2006agV1.loc[cne2006agV1['SEXO'] == "2" , 'VOTOS_NULOS']

# Llenar con NaN en caso de que no haya datos para una categoría
cne2006agV1['VOTOS_NULOS_M'] = cne2006agV1['VOTOS_NULOS_M'].fillna(0)
cne2006agV1['VOTOS_NULOS_F'] = cne2006agV1['VOTOS_NULOS_F'].fillna(0)

cne2006agV1 = cne2006agV1.drop("VOTOS_NULOS", axis=1)

# Crear columnas separadas
cne2006agV1['VOTOS_BLANCOS_M'] = cne2006agV1.loc[cne2006agV1['SEXO'] == 1 , 'VOTOS_EN_BLANCO']
cne2006agV1['VOTOS_BLANCOS_F'] = cne2006agV1.loc[cne2006agV1['SEXO'] == 2 , 'VOTOS_EN_BLANCO']

# Llenar con NaN en caso de que no haya datos para una categoría
cne2006agV1['VOTOS_BLANCOS_M'] = cne2006agV1['VOTOS_BLANCOS_M'].fillna(0)
cne2006agV1['VOTOS_BLANCOS_F'] = cne2006agV1['VOTOS_BLANCOS_F'].fillna(0)

cne2006agV1 = cne2006agV1.drop("VOTOS_EN_BLANCO", axis=1)

# Crear columnas separadas
cne2006agV1['VOTOS_CANDIDATO_M'] = cne2006agV1.loc[cne2006agV1['SEXO'] == 1 , 'CANDIDATO_VOTOS']
cne2006agV1['VOTOS_CANDIDATO_F'] = cne2006agV1.loc[cne2006agV1['SEXO'] == 2 , 'CANDIDATO_VOTOS']

# Llenar con NaN en caso de que no haya datos para una categoría
cne2006agV1['VOTOS_CANDIDATO_M'] = cne2006agV1['VOTOS_CANDIDATO_M'].fillna(0)
cne2006agV1['VOTOS_CANDIDATO_F'] = cne2006agV1['VOTOS_CANDIDATO_F'].fillna(0)

cne2006agV1 = cne2006agV1.drop("CANDIDATO_VOTOS", axis=1)

In [24]:
cne2006agV1.drop(columns=['SEXO_DESCRIPCION'],inplace=True)

In [25]:
cne2006agV1

,CANTON_CODIGO,CANDIDATO_CODIGO,NUMERO_DE_ACTAS,SEXO,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,VOTOS_CANDIDATO_M,VOTOS_CANDIDATO_F
0,5.0,1.000000e+12,99,1,0.0,0.0,900.0,0.0,683.0,0.0
1,5.0,1.000000e+12,101,2,0.0,0.0,0.0,961.0,0.0,959.0
2,5.0,1.000000e+12,99,1,0.0,0.0,900.0,0.0,45.0,0.0
3,5.0,1.000000e+12,101,2,0.0,0.0,0.0,961.0,0.0,32.0
4,5.0,1.000000e+12,99,1,0.0,0.0,900.0,0.0,948.0,0.0
...,...,...,...,...,...,...,...,...,...,...
6781,995.0,1.000000e+12,10,2,0.0,0.0,0.0,99.0,0.0,40.0
6782,995.0,1.000000e+12,10,1,0.0,0.0,99.0,0.0,705.0,0.0
6783,995.0,1.000000e+12,10,2,0.0,0.0,0.0,99.0,0.0,525.0
6784,995.0,1.000000e+12,10,1,0.0,0.0,99.0,0.0,5.0,0.0
6785,995.0,1.000000e+12,10,2,0.0,0.0,0.0,99.0,0.0,4.0

In [26]:
cne2006agV1 = cne2006agV1.drop("SEXO", axis=1)

In [27]:
cne2006agFV1 = cne2006agV1.groupby(['CANTON_CODIGO','CANDIDATO_CODIGO']).agg({
    'NUMERO_DE_ACTAS': 'sum',
    'VOTOS_NULOS_M': 'sum',
    'VOTOS_NULOS_F': 'sum',
    'VOTOS_BLANCOS_M': 'sum',
     'VOTOS_BLANCOS_F': 'sum',
    'VOTOS_CANDIDATO_M': 'sum',
    'VOTOS_CANDIDATO_F': 'sum'

}).reset_index()

cne2006agFV1

,CANTON_CODIGO,CANDIDATO_CODIGO,NUMERO_DE_ACTAS,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,VOTOS_CANDIDATO_M,VOTOS_CANDIDATO_F
0,5.0,1.000000e+12,200,0.0,0.0,900.0,961.0,683.0,959.0
1,5.0,1.000000e+12,200,0.0,0.0,900.0,961.0,45.0,32.0
2,5.0,1.000000e+12,200,0.0,0.0,900.0,961.0,948.0,1513.0
3,5.0,1.000000e+12,200,0.0,0.0,900.0,961.0,7168.0,7785.0
4,5.0,1.000000e+12,200,0.0,0.0,900.0,961.0,177.0,130.0
...,...,...,...,...,...,...,...,...,...
3388,995.0,1.000000e+12,20,0.0,0.0,99.0,99.0,64.0,48.0
3389,995.0,1.000000e+12,20,0.0,0.0,99.0,99.0,2.0,4.0
3390,995.0,1.000000e+12,20,0.0,0.0,99.0,99.0,29.0,40.0
3391,995.0,1.000000e+12,20,0.0,0.0,99.0,99.0,705.0,525.0
3392,995.0,1.000000e+12,20,0.0,0.0,99.0,99.0,5.0,4.0

In [28]:
# Agregar la columna "AÑO" con valor 2004 al principio del dataframe
cne2006agFV1.insert(0, "AÑO", 2006)

# Agregar la columna "VUELTA" con valor 2 al principio del dataframe
cne2006agFV1.insert(1, "VUELTA", 1)

In [29]:
cne2006agFV1

,AÑO,VUELTA,CANTON_CODIGO,CANDIDATO_CODIGO,NUMERO_DE_ACTAS,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,VOTOS_CANDIDATO_M,VOTOS_CANDIDATO_F
0,2006,1,5.0,1.000000e+12,200,0.0,0.0,900.0,961.0,683.0,959.0
1,2006,1,5.0,1.000000e+12,200,0.0,0.0,900.0,961.0,45.0,32.0
2,2006,1,5.0,1.000000e+12,200,0.0,0.0,900.0,961.0,948.0,1513.0
3,2006,1,5.0,1.000000e+12,200,0.0,0.0,900.0,961.0,7168.0,7785.0
4,2006,1,5.0,1.000000e+12,200,0.0,0.0,900.0,961.0,177.0,130.0
...,...,...,...,...,...,...,...,...,...,...,...
3388,2006,1,995.0,1.000000e+12,20,0.0,0.0,99.0,99.0,64.0,48.0
3389,2006,1,995.0,1.000000e+12,20,0.0,0.0,99.0,99.0,2.0,4.0
3390,2006,1,995.0,1.000000e+12,20,0.0,0.0,99.0,99.0,29.0,40.0
3391,2006,1,995.0,1.000000e+12,20,0.0,0.0,99.0,99.0,705.0,525.0
3392,2006,1,995.0,1.000000e+12,20,0.0,0.0,99.0,99.0,5.0,4.0

### Registro Electoral 2002 (CNE)
Analizar el archivo "registro electoral a nivel parroquial 2002.sav" para obtener el número de electores por parroquia.

In [30]:
cne2006RPA = pd.read_spss("../raw/registro electoral/registro electoral a nivel parroquial 2006.sav")
cne2006RPA

,PROVINCIA_CODIGO,CANTON_CODIGO,PARROQUIA_CODIGO,SEXO,GRANDES_GRUPOS_DE_EDAD_1V,ELECTORES
0,1.0,260.0,285.0,HOMBRES,DE 18 A MENOS DE 65 AÑOS,6701.0
1,1.0,260.0,285.0,HOMBRES,DE 65 AÑOS Y MÁS,601.0
2,1.0,260.0,285.0,MUJERES,DE 18 A MENOS DE 65 AÑOS,6666.0
3,1.0,260.0,285.0,MUJERES,DE 65 AÑOS Y MÁS,728.0
4,1.0,260.0,730.0,HOMBRES,DE 18 A MENOS DE 65 AÑOS,2070.0
...,...,...,...,...,...,...
4902,28.0,391.0,9061.0,MUJERES,DE 18 A MENOS DE 65 AÑOS,17.0
4903,28.0,401.0,9062.0,HOMBRES,DE 18 A MENOS DE 65 AÑOS,1799.0
4904,28.0,401.0,9062.0,HOMBRES,DE 65 AÑOS Y MÁS,71.0
4905,28.0,401.0,9062.0,MUJERES,DE 18 A MENOS DE 65 AÑOS,1942.0
4906,28.0,401.0,9062.0,MUJERES,DE 65 AÑOS Y MÁS,63.0

In [31]:
cne2006RPA = cne2006RPA.groupby(['CANTON_CODIGO', 'SEXO' ]).agg({
    'ELECTORES': 'sum',

}).reset_index()

cne2006RPA=cne2006RPA.rename(columns = {'SEXO':'SEXO_DESCRIPCION'})

cne2006RPA['SEXO'] = cne2006RPA['SEXO_DESCRIPCION'].map({'HOMBRES':1,'MUJERES':2})
cne2006RPA

     CANTON_CODIGO SEXO_DESCRIPCION  ELECTORES SEXO
0              5.0          HOMBRES    28887.0    1
1              5.0          MUJERES    29423.0    2
2             10.0          HOMBRES    11161.0    1
3             10.0          MUJERES    11774.0    2
4             11.0          HOMBRES      184.0    1
..             ...              ...        ...  ...
517          986.0          MUJERES     2571.0    2
518          990.0          HOMBRES     1224.0    1
519          990.0          MUJERES     1311.0    2
520          995.0          HOMBRES     2803.0    1
521          995.0          MUJERES     2798.0    2

[522 rows x 4 columns]

In [32]:
cne2006RPA.drop(columns=['SEXO_DESCRIPCION'],inplace=True)

In [33]:
# Crear columnas separadas
cne2006RPA['ELECTORES_M'] = cne2006RPA.loc[cne2006RPA['SEXO'] == 1 , 'ELECTORES']
cne2006RPA['ELECTORAS_F'] = cne2006RPA.loc[cne2006RPA['SEXO'] == 2 , 'ELECTORES']

# Llenar con NaN en caso de que no haya datos para una categoría
cne2006RPA['ELECTORES_M'] = cne2006RPA['ELECTORES_M'].fillna(0)
cne2006RPA['ELECTORAS_F'] = cne2006RPA['ELECTORAS_F'].fillna(0)

cne2006RPA = cne2006RPA.drop("ELECTORES", axis=1)

cne2006RPA

     CANTON_CODIGO SEXO  ELECTORES_M  ELECTORAS_F
0              5.0    1      28887.0          0.0
1              5.0    2          0.0      29423.0
2             10.0    1      11161.0          0.0
3             10.0    2          0.0      11774.0
4             11.0    1        184.0          0.0
..             ...  ...          ...          ...
517          986.0    2          0.0       2571.0
518          990.0    1       1224.0          0.0
519          990.0    2          0.0       1311.0
520          995.0    1       2803.0          0.0
521          995.0    2          0.0       2798.0

[522 rows x 4 columns]

In [34]:
cne2006RPA.drop('SEXO', axis=1)
cne2006RPA = cne2006RPA.groupby(['CANTON_CODIGO']).agg({
    'ELECTORES_M': 'sum',
    'ELECTORAS_F': 'sum'

}).reset_index()

cne2006RPA

     CANTON_CODIGO  ELECTORES_M  ELECTORAS_F
0              5.0      28887.0      29423.0
1             10.0      11161.0      11774.0
2             11.0        184.0        343.0
3             15.0       5424.0       5741.0
4             20.0       4855.0       4797.0
..             ...          ...          ...
256          981.0        866.0        784.0
257          985.0       3509.0       3227.0
258          986.0       2875.0       2571.0
259          990.0       1224.0       1311.0
260          995.0       2803.0       2798.0

[261 rows x 3 columns]

### Listado de Candidatos

In [35]:
#importar la base de datos de candidatos
cne2006candidatosV1= pd.read_spss("../raw/organizaciones politicas/CANDIDATOS (1).sav")

In [36]:
cne2006candidatosV1['CANDIDATO_NOMBRE'].value_counts()

CASTILLO RICARDO                2
CAIZAGUANO ANGELICA             2
GARCIA MARIA                    2
GONZALEZ LUIS                   2
CASTRO GONZALO                  2
                               ..
CASTILLO QUINTERO ECILDA EVA    1
CAICEDO RODRIGUEZ RICHARD       1
PEREA ESTACIO YONIS             1
RAMIREZ SOLIZ CATALINA          1
TAPIA V DIEGO RICARDO           1
Name: CANDIDATO_NOMBRE, Length: 8690, dtype: int64

In [37]:
#Crear un nuevo dataframe con las columnas deseadas
cne2006c = cne2006candidatosV1[['OP_CODIGO', 'CANDIDATO_CODIGO', 'CANDIDATO_NOMBRE', 'CANDIDATO_SEXO', 'CANDIDATO_EDAD','DIGNIDAD_CODIGO']].copy()

cne2006c["CANDIDATO_SEXO"] = cne2006c["CANDIDATO_SEXO"].replace(1.0, "MASCULINO")
cne2006c["CANDIDATO_SEXO"] = cne2006c["CANDIDATO_SEXO"].replace(2.0, "FEMENINO")

# Convertir el tipo de datos de la columna 'OP_CODIGO' a string en el DataFrame 'cne2006c'
cne2006c["DIGNIDAD_CODIGO"] = cne2006c["DIGNIDAD_CODIGO"].astype(int)

cne2006c["CANDIDATO_EDAD"] = cne2006c["CANDIDATO_EDAD"].astype(int)

cne2006c["OP_CODIGO"] = cne2006c["OP_CODIGO"].astype(int)
# no castear como int porque sucede un overflow
#cne2006c["CANDIDATO_CODIGO"] = cne2006c["CANDIDATO_CODIGO"].astype(int)

#Filtrar por candidatos a presidente (Digindad 1)
cne2006c=cne2006c[cne2006candidatosV1['DIGNIDAD_CODIGO']==1.0]

In [38]:
# Mostrar el nuevo dataframe
cne2006c.columns

Index(['OP_CODIGO', 'CANDIDATO_CODIGO', 'CANDIDATO_NOMBRE', 'CANDIDATO_SEXO',
       'CANDIDATO_EDAD', 'DIGNIDAD_CODIGO'],
      dtype='object')

In [39]:
cne2006c

,OP_CODIGO,CANDIDATO_CODIGO,CANDIDATO_NOMBRE,CANDIDATO_SEXO,CANDIDATO_EDAD,DIGNIDAD_CODIGO
0,48,1.000000e+12,GUTIERREZ GILMAR,HOMBRES,38,1
1,1,1.000000e+12,DAMERVAL JAIME,HOMBRES,65,1
2,4,1.000000e+12,VITERI CYNTHIA,MUJERES,40,1
3,5,1.000000e+12,NOBOA ALVARO,HOMBRES,55,1
4,6,1.000000e+12,ROSERO FERNANDO,HOMBRES,57,1
5,71,1.000000e+12,ROLDOS AGUILERA LEON,HOMBRES,64,1
6,24,1.000000e+12,SAGNAY DE LA BASTIDA CARLOS,HOMBRES,50,1
7,8,1.000000e+12,VILLACIS LUIS,HOMBRES,54,1
8,10,1.000000e+12,MACAS LUIS,HOMBRES,56,1
9,16,1.000000e+12,TORRES LENIN,HOMBRES,71,1
10,55,1.000000e+12,PROAÑO MAYA MARCO,HOMBRES,61,1
11,72,1.000000e+12,CORREA DELGADO RAFAEL,HOMBRES,43,1
12,62,1.000000e+12,LARREA CABRERA MARCELO,HOMBRES,46,1

In [40]:
cne2006agFV1['CANDIDATO_CODIGO'] = cne2006agFV1['CANDIDATO_CODIGO'].astype(float)
cne2006c['CANDIDATO_CODIGO'] = cne2006c['CANDIDATO_CODIGO'].astype(float)

In [41]:
cne2006agFV1['CANDIDATO_NOMBRE'] = cne2006agFV1['CANDIDATO_CODIGO'].map(cne2006c.set_index('CANDIDATO_CODIGO')['CANDIDATO_NOMBRE'])
cne2006agFV1['CANDIDATO_EDAD'] = cne2006agFV1['CANDIDATO_CODIGO'].map(cne2006c.set_index('CANDIDATO_CODIGO')['CANDIDATO_EDAD'])
cne2006agFV1['CANDIDATO_SEXO'] = cne2006agFV1['CANDIDATO_CODIGO'].map(cne2006c.set_index('CANDIDATO_CODIGO')['CANDIDATO_SEXO'])
cne2006agFV1['OP_CODIGO'] = cne2006agFV1['CANDIDATO_CODIGO'].map(cne2006c.set_index('CANDIDATO_CODIGO')['OP_CODIGO'])

cne2006agFV1

,AÑO,VUELTA,CANTON_CODIGO,CANDIDATO_CODIGO,NUMERO_DE_ACTAS,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,VOTOS_CANDIDATO_M,VOTOS_CANDIDATO_F,CANDIDATO_NOMBRE,CANDIDATO_EDAD,CANDIDATO_SEXO,OP_CODIGO
0,2006,1,5.0,1.000000e+12,200,0.0,0.0,900.0,961.0,683.0,959.0,GUTIERREZ GILMAR,38,HOMBRES,48
1,2006,1,5.0,1.000000e+12,200,0.0,0.0,900.0,961.0,45.0,32.0,DAMERVAL JAIME,65,HOMBRES,1
2,2006,1,5.0,1.000000e+12,200,0.0,0.0,900.0,961.0,948.0,1513.0,VITERI CYNTHIA,40,MUJERES,4
3,2006,1,5.0,1.000000e+12,200,0.0,0.0,900.0,961.0,7168.0,7785.0,NOBOA ALVARO,55,HOMBRES,5
4,2006,1,5.0,1.000000e+12,200,0.0,0.0,900.0,961.0,177.0,130.0,ROSERO FERNANDO,57,HOMBRES,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3388,2006,1,995.0,1.000000e+12,20,0.0,0.0,99.0,99.0,64.0,48.0,MACAS LUIS,56,HOMBRES,10
3389,2006,1,995.0,1.000000e+12,20,0.0,0.0,99.0,99.0,2.0,4.0,TORRES LENIN,71,HOMBRES,16
3390,2006,1,995.0,1.000000e+12,20,0.0,0.0,99.0,99.0,29.0,40.0,PROAÑO MAYA MARCO,61,HOMBRES,55
3391,2006,1,995.0,1.000000e+12,20,0.0,0.0,99.0,99.0,705.0,525.0,CORREA DELGADO RAFAEL,43,HOMBRES,72
3392,2006,1,995.0,1.000000e+12,20,0.0,0.0,99.0,99.0,5.0,4.0,LARREA CABRERA MARCELO,46,HOMBRES,62

In [42]:
cne2006agFV1['CANTON_CODIGO'] = cne2006agFV1['CANTON_CODIGO'].astype(int)
cne2006RPA['CANTON_CODIGO'] = cne2006RPA['CANTON_CODIGO'].astype(int)

In [43]:
cne2006agFV1['ELECTORES_M'] = cne2006agFV1['CANTON_CODIGO'].map(cne2006RPA.set_index('CANTON_CODIGO')['ELECTORES_M'])
cne2006agFV1['ELECTORAS_F'] = cne2006agFV1['CANTON_CODIGO'].map(cne2006RPA.set_index('CANTON_CODIGO')['ELECTORAS_F'])

cne2006agFV1

,AÑO,VUELTA,CANTON_CODIGO,CANDIDATO_CODIGO,NUMERO_DE_ACTAS,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,VOTOS_CANDIDATO_M,VOTOS_CANDIDATO_F,CANDIDATO_NOMBRE,CANDIDATO_EDAD,CANDIDATO_SEXO,OP_CODIGO,ELECTORES_M,ELECTORAS_F
0,2006,1,5,1.000000e+12,200,0.0,0.0,900.0,961.0,683.0,959.0,GUTIERREZ GILMAR,38,HOMBRES,48,28887.0,29423.0
1,2006,1,5,1.000000e+12,200,0.0,0.0,900.0,961.0,45.0,32.0,DAMERVAL JAIME,65,HOMBRES,1,28887.0,29423.0
2,2006,1,5,1.000000e+12,200,0.0,0.0,900.0,961.0,948.0,1513.0,VITERI CYNTHIA,40,MUJERES,4,28887.0,29423.0
3,2006,1,5,1.000000e+12,200,0.0,0.0,900.0,961.0,7168.0,7785.0,NOBOA ALVARO,55,HOMBRES,5,28887.0,29423.0
4,2006,1,5,1.000000e+12,200,0.0,0.0,900.0,961.0,177.0,130.0,ROSERO FERNANDO,57,HOMBRES,6,28887.0,29423.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3388,2006,1,995,1.000000e+12,20,0.0,0.0,99.0,99.0,64.0,48.0,MACAS LUIS,56,HOMBRES,10,2803.0,2798.0
3389,2006,1,995,1.000000e+12,20,0.0,0.0,99.0,99.0,2.0,4.0,TORRES LENIN,71,HOMBRES,16,2803.0,2798.0
3390,2006,1,995,1.000000e+12,20,0.0,0.0,99.0,99.0,29.0,40.0,PROAÑO MAYA MARCO,61,HOMBRES,55,2803.0,2798.0
3391,2006,1,995,1.000000e+12,20,0.0,0.0,99.0,99.0,705.0,525.0,CORREA DELGADO RAFAEL,43,HOMBRES,72,2803.0,2798.0
3392,2006,1,995,1.000000e+12,20,0.0,0.0,99.0,99.0,5.0,4.0,LARREA CABRERA MARCELO,46,HOMBRES,62,2803.0,2798.0

### Análizar Organizaciones Políticas

In [44]:
# Crear un nuevo dataframe a partir del archivo 'organizaciones_politicas_2002.sav'
cne2006op= pd.read_spss("../raw/organizaciones politicas/organizaciones polticas 2006.sav")

In [45]:
cne2006op

,OP_CODIGO,OP_PROVINCIA_CODIGO,OP_CANTON_CODIGO,OP_PARROQUIA_CODIGO,OP_TIPO,OP_AMBITO,OP_NOMBRE,OP_SIGLAS,OP_LISTA
0,1.0,0.0,0.0,0.0,PARTIDOS POLITICOS,NACIONAL,CONCENTRACION DE FUERZAS POPULARES,CFP,4
1,3.0,0.0,0.0,0.0,PARTIDOS POLITICOS,NACIONAL,UNION DEMOCRATA CRISTIANA,UDC,5
2,4.0,0.0,0.0,0.0,PARTIDOS POLITICOS,NACIONAL,PARTIDO SOCIAL CRISTIANO,PSC,6
3,5.0,0.0,0.0,0.0,PARTIDOS POLITICOS,NACIONAL,PARTIDO RENOVADOR INSTITUCIONAL ACCION NACIONAL,PRIAN,7
4,6.0,0.0,0.0,0.0,PARTIDOS POLITICOS,NACIONAL,PARTIDO ROLDOSISTA ECUATORIANO,PRE,10
...,...,...,...,...,...,...,...,...,...
232,22010.0,22.0,0.0,0.0,ALIANZAS,ALIANZA,ALIANZA PSC/AA,PSC/AA,6-62
233,22011.0,22.0,0.0,0.0,MOV. INDEPENDIENTES PROVINCIALES,PROVINCIAL,MOVIMIENTO INDEPENDIENTE AMAUTA,MIA,63
234,22012.0,22.0,0.0,0.0,ALIANZAS,ALIANZA,ALIANZA PSC/PRE/AA,PSC/PRE/AA,6-10-62
235,22013.0,22.0,0.0,0.0,ALIANZAS,ALIANZA,ALIANZA PRE/PSC/AA,PRE/PSC/AA,10-6-62
236,22014.0,22.0,0.0,0.0,ALIANZAS,ALIANZA,ALIANZA UDC/MUPP-NP/MIA,UDC/MUPP-NP/MIA,5-18-63

In [46]:
cne2006agFV1['OP_TIPO'] = cne2006agFV1['OP_CODIGO'].map(cne2006op.set_index('OP_CODIGO')['OP_TIPO'])
cne2006agFV1['OP_AMBITO'] = cne2006agFV1['OP_CODIGO'].map(cne2006op.set_index('OP_CODIGO')['OP_AMBITO'])
cne2006agFV1['OP_NOMBRE'] = cne2006agFV1['OP_CODIGO'].map(cne2006op.set_index('OP_CODIGO')['OP_NOMBRE'])
cne2006agFV1['OP_SIGLAS'] = cne2006agFV1['OP_CODIGO'].map(cne2006op.set_index('OP_CODIGO')['OP_SIGLAS'])

cne2006agFV1

,AÑO,VUELTA,CANTON_CODIGO,CANDIDATO_CODIGO,NUMERO_DE_ACTAS,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,VOTOS_CANDIDATO_M,...,CANDIDATO_NOMBRE,CANDIDATO_EDAD,CANDIDATO_SEXO,OP_CODIGO,ELECTORES_M,ELECTORAS_F,OP_TIPO,OP_AMBITO,OP_NOMBRE,OP_SIGLAS
0,2006,1,5,1.000000e+12,200,0.0,0.0,900.0,961.0,683.0,...,GUTIERREZ GILMAR,38,HOMBRES,48,28887.0,29423.0,PARTIDOS POLITICOS,NACIONAL,PARTIDO SOCIEDAD PATRIOTICA,PSP
1,2006,1,5,1.000000e+12,200,0.0,0.0,900.0,961.0,45.0,...,DAMERVAL JAIME,65,HOMBRES,1,28887.0,29423.0,PARTIDOS POLITICOS,NACIONAL,CONCENTRACION DE FUERZAS POPULARES,CFP
2,2006,1,5,1.000000e+12,200,0.0,0.0,900.0,961.0,948.0,...,VITERI CYNTHIA,40,MUJERES,4,28887.0,29423.0,PARTIDOS POLITICOS,NACIONAL,PARTIDO SOCIAL CRISTIANO,PSC
3,2006,1,5,1.000000e+12,200,0.0,0.0,900.0,961.0,7168.0,...,NOBOA ALVARO,55,HOMBRES,5,28887.0,29423.0,PARTIDOS POLITICOS,NACIONAL,PARTIDO RENOVADOR INSTITUCIONAL ACCION NACIONAL,PRIAN
4,2006,1,5,1.000000e+12,200,0.0,0.0,900.0,961.0,177.0,...,ROSERO FERNANDO,57,HOMBRES,6,28887.0,29423.0,PARTIDOS POLITICOS,NACIONAL,PARTIDO ROLDOSISTA ECUATORIANO,PRE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3388,2006,1,995,1.000000e+12,20,0.0,0.0,99.0,99.0,64.0,...,MACAS LUIS,56,HOMBRES,10,2803.0,2798.0,MOV. INDEPENDIENTES NACIONALES,NACIONAL,MOVIMIENTO UNIDAD PLURINACIONAL PACHAKUTIK - N...,MUPP-NP
3389,2006,1,995,1.000000e+12,20,0.0,0.0,99.0,99.0,2.0,...,TORRES LENIN,71,HOMBRES,16,2803.0,2798.0,MOV. INDEPENDIENTES NACIONALES,NACIONAL,MOVIMIENTO REVOLUCIONARIO DE PARTICIPACION POP...,MRPP
3390,2006,1,995,1.000000e+12,20,0.0,0.0,99.0,99.0,29.0,...,PROAÑO MAYA MARCO,61,HOMBRES,55,2803.0,2798.0,MOV. INDEPENDIENTES NACIONALES,NACIONAL,MOVIMIENTO DE LA REIVINDICACION DEMOCRATICA,MRD
3391,2006,1,995,1.000000e+12,20,0.0,0.0,99.0,99.0,705.0,...,CORREA DELGADO RAFAEL,43,HOMBRES,72,2803.0,2798.0,ALIANZAS,ALIANZA,ALIANZA MPAIS/PS-FA,MPAIS/PS-FA
3392,2006,1,995,1.000000e+12,20,0.0,0.0,99.0,99.0,5.0,...,LARREA CABRERA MARCELO,46,HOMBRES,62,2803.0,2798.0,MOV. INDEPENDIENTES NACIONALES,NACIONAL,MOVIMIENTO ALIANZA TERCERA REPUBLICA ALBA,ATR

In [47]:

cne2006agFV1['OP_CODIGO'] = cne2006agFV1['OP_CODIGO'].astype(int)

In [48]:
# Mostrar el DataFrame resultante
cne2006agFV1.columns

Index(['AÑO', 'VUELTA', 'CANTON_CODIGO', 'CANDIDATO_CODIGO', 'NUMERO_DE_ACTAS',
       'VOTOS_NULOS_M', 'VOTOS_NULOS_F', 'VOTOS_BLANCOS_M', 'VOTOS_BLANCOS_F',
       'VOTOS_CANDIDATO_M', 'VOTOS_CANDIDATO_F', 'CANDIDATO_NOMBRE',
       'CANDIDATO_EDAD', 'CANDIDATO_SEXO', 'OP_CODIGO', 'ELECTORES_M',
       'ELECTORAS_F', 'OP_TIPO', 'OP_AMBITO', 'OP_NOMBRE', 'OP_SIGLAS'],
      dtype='object')

In [49]:
cne2006agFV1['CANDIDATO_CODIGO'] = cne2006agFV1['CANDIDATO_CODIGO'].map(cne2006c.set_index('CANDIDATO_CODIGO')['OP_CODIGO'])
cne2006agFV1=cne2006agFV1.rename(columns = {'CANDIDATO_CODIGO':'OP_CODIGO'})

In [50]:
cne2006agFV1

,AÑO,VUELTA,CANTON_CODIGO,OP_CODIGO,NUMERO_DE_ACTAS,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,VOTOS_CANDIDATO_M,...,CANDIDATO_NOMBRE,CANDIDATO_EDAD,CANDIDATO_SEXO,OP_CODIGO,ELECTORES_M,ELECTORAS_F,OP_TIPO,OP_AMBITO,OP_NOMBRE,OP_SIGLAS
0,2006,1,5,48,200,0.0,0.0,900.0,961.0,683.0,...,GUTIERREZ GILMAR,38,HOMBRES,48,28887.0,29423.0,PARTIDOS POLITICOS,NACIONAL,PARTIDO SOCIEDAD PATRIOTICA,PSP
1,2006,1,5,1,200,0.0,0.0,900.0,961.0,45.0,...,DAMERVAL JAIME,65,HOMBRES,1,28887.0,29423.0,PARTIDOS POLITICOS,NACIONAL,CONCENTRACION DE FUERZAS POPULARES,CFP
2,2006,1,5,4,200,0.0,0.0,900.0,961.0,948.0,...,VITERI CYNTHIA,40,MUJERES,4,28887.0,29423.0,PARTIDOS POLITICOS,NACIONAL,PARTIDO SOCIAL CRISTIANO,PSC
3,2006,1,5,5,200,0.0,0.0,900.0,961.0,7168.0,...,NOBOA ALVARO,55,HOMBRES,5,28887.0,29423.0,PARTIDOS POLITICOS,NACIONAL,PARTIDO RENOVADOR INSTITUCIONAL ACCION NACIONAL,PRIAN
4,2006,1,5,6,200,0.0,0.0,900.0,961.0,177.0,...,ROSERO FERNANDO,57,HOMBRES,6,28887.0,29423.0,PARTIDOS POLITICOS,NACIONAL,PARTIDO ROLDOSISTA ECUATORIANO,PRE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3388,2006,1,995,10,20,0.0,0.0,99.0,99.0,64.0,...,MACAS LUIS,56,HOMBRES,10,2803.0,2798.0,MOV. INDEPENDIENTES NACIONALES,NACIONAL,MOVIMIENTO UNIDAD PLURINACIONAL PACHAKUTIK - N...,MUPP-NP
3389,2006,1,995,16,20,0.0,0.0,99.0,99.0,2.0,...,TORRES LENIN,71,HOMBRES,16,2803.0,2798.0,MOV. INDEPENDIENTES NACIONALES,NACIONAL,MOVIMIENTO REVOLUCIONARIO DE PARTICIPACION POP...,MRPP
3390,2006,1,995,55,20,0.0,0.0,99.0,99.0,29.0,...,PROAÑO MAYA MARCO,61,HOMBRES,55,2803.0,2798.0,MOV. INDEPENDIENTES NACIONALES,NACIONAL,MOVIMIENTO DE LA REIVINDICACION DEMOCRATICA,MRD
3391,2006,1,995,72,20,0.0,0.0,99.0,99.0,705.0,...,CORREA DELGADO RAFAEL,43,HOMBRES,72,2803.0,2798.0,ALIANZAS,ALIANZA,ALIANZA MPAIS/PS-FA,MPAIS/PS-FA
3392,2006,1,995,62,20,0.0,0.0,99.0,99.0,5.0,...,LARREA CABRERA MARCELO,46,HOMBRES,62,2803.0,2798.0,MOV. INDEPENDIENTES NACIONALES,NACIONAL,MOVIMIENTO ALIANZA TERCERA REPUBLICA ALBA,ATR

In [51]:
cne2006agFV1['OP_CODIGO'] = cne2006agFV1['OP_CODIGO'].astype(int)

### Generar columnas de votos por candidato y por género

In [52]:
# Creacion de un diccionario con los nombres de los candidatos y los codigos de sus organizaciones politicas
candidatos_dict = dict(zip(cne2006c['CANDIDATO_NOMBRE'], cne2006c['OP_CODIGO']))

#Imprime el diccionario
print(candidatos_dict)
candidatos_dict

{'GUTIERREZ GILMAR': 48, 'DAMERVAL  JAIME': 1, 'VITERI  CYNTHIA': 4, 'NOBOA ALVARO': 5, 'ROSERO  FERNANDO': 6, 'ROLDOS AGUILERA LEON': 71, 'SAGNAY DE LA BASTIDA CARLOS': 24, 'VILLACIS LUIS': 8, 'MACAS  LUIS': 10, 'TORRES LENIN': 16, 'PROAÑO MAYA MARCO': 55, 'CORREA DELGADO RAFAEL': 72, 'LARREA CABRERA MARCELO': 62}

{'GUTIERREZ GILMAR': 48,
 'DAMERVAL  JAIME': 1,
 'VITERI  CYNTHIA': 4,
 'NOBOA ALVARO': 5,
 'ROSERO  FERNANDO': 6,
 'ROLDOS AGUILERA LEON': 71,
 'SAGNAY DE LA BASTIDA CARLOS': 24,
 'VILLACIS LUIS': 8,
 'MACAS  LUIS': 10,
 'TORRES LENIN': 16,
 'PROAÑO MAYA MARCO': 55,
 'CORREA DELGADO RAFAEL': 72,
 'LARREA CABRERA MARCELO': 62}

In [53]:
# to do Crear funcion para crear nuevas columnas con el apellido del candidato y los votos por sexo
# pero esta version ya es funcional

# 
#itera sobre el diccionario y crea las nuevas columnas
for candidato, codigo in candidatos_dict.items():
    columna_m = f'VC_{candidato.split()[0]}_M'
    columna_f = f'VC_{candidato.split()[0]}_F'
    cne2006agFV1[columna_m]= cne2006agFV1.loc[cne2006agFV1['CANDIDATO_NOMBRE'] == candidato, 'VOTOS_CANDIDATO_M']
    cne2006agFV1[columna_f]= cne2006agFV1.loc[cne2006agFV1['CANDIDATO_NOMBRE'] == candidato, 'VOTOS_CANDIDATO_F']
    cne2006agFV1[columna_f]= cne2006agFV1[columna_f].fillna(0)
    cne2006agFV1[columna_m]= cne2006agFV1[columna_m].fillna(0)

#Verifica los cambios
cne2006agFV1

,AÑO,VUELTA,CANTON_CODIGO,OP_CODIGO,NUMERO_DE_ACTAS,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,VOTOS_CANDIDATO_M,...,VC_MACAS_M,VC_MACAS_F,VC_TORRES_M,VC_TORRES_F,VC_PROAÑO_M,VC_PROAÑO_F,VC_CORREA_M,VC_CORREA_F,VC_LARREA_M,VC_LARREA_F
0,2006,1,5,48,200,0.0,0.0,900.0,961.0,683.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2006,1,5,1,200,0.0,0.0,900.0,961.0,45.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2006,1,5,4,200,0.0,0.0,900.0,961.0,948.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2006,1,5,5,200,0.0,0.0,900.0,961.0,7168.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2006,1,5,6,200,0.0,0.0,900.0,961.0,177.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3388,2006,1,995,10,20,0.0,0.0,99.0,99.0,64.0,...,64.0,48.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3389,2006,1,995,16,20,0.0,0.0,99.0,99.0,2.0,...,0.0,0.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
3390,2006,1,995,55,20,0.0,0.0,99.0,99.0,29.0,...,0.0,0.0,0.0,0.0,29.0,40.0,0.0,0.0,0.0,0.0
3391,2006,1,995,72,20,0.0,0.0,99.0,99.0,705.0,...,0.0,0.0,0.0,0.0,0.0,0.0,705.0,525.0,0.0,0.0
3392,2006,1,995,62,20,0.0,0.0,99.0,99.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,4.0

In [54]:
cne2006agFV1.dtypes

AÑO                     int64
VUELTA                  int64
CANTON_CODIGO           int32
OP_CODIGO               int32
NUMERO_DE_ACTAS         int32
VOTOS_NULOS_M         float64
VOTOS_NULOS_F         float64
VOTOS_BLANCOS_M       float64
VOTOS_BLANCOS_F       float64
VOTOS_CANDIDATO_M     float64
VOTOS_CANDIDATO_F     float64
CANDIDATO_NOMBRE       object
CANDIDATO_EDAD          int32
CANDIDATO_SEXO       category
OP_CODIGO               int32
ELECTORES_M           float64
ELECTORAS_F           float64
OP_TIPO                object
OP_AMBITO              object
OP_NOMBRE              object
OP_SIGLAS              object
VC_GUTIERREZ_M        float64
VC_GUTIERREZ_F        float64
VC_DAMERVAL_M         float64
VC_DAMERVAL_F         float64
VC_VITERI_M           float64
VC_VITERI_F           float64
VC_NOBOA_M            float64
VC_NOBOA_F            float64
VC_ROSERO_M           float64
VC_ROSERO_F           float64
VC_ROLDOS_M           float64
VC_ROLDOS_F           float64
VC_SAGNAY_M           float64
VC_SAGNAY_F           float64
VC_VILLACIS_M         float64
VC_VILLACIS_F         float64
VC_MACAS_M            float64
VC_MACAS_F            float64
VC_TORRES_M           float64
VC_TORRES_F           float64
VC_PROAÑO_M           float64
VC_PROAÑO_F           float64
VC_CORREA_M           float64
VC_CORREA_F           float64
VC_LARREA_M           float64
VC_LARREA_F           float64
dtype: object

In [55]:
cne2006agFV1 = cne2006agFV1.drop("VOTOS_CANDIDATO_F", axis=1)
cne2006agFV1 = cne2006agFV1.drop("VOTOS_CANDIDATO_M", axis=1)

In [56]:
cne2006agFV1

,AÑO,VUELTA,CANTON_CODIGO,OP_CODIGO,NUMERO_DE_ACTAS,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,CANDIDATO_NOMBRE,...,VC_MACAS_M,VC_MACAS_F,VC_TORRES_M,VC_TORRES_F,VC_PROAÑO_M,VC_PROAÑO_F,VC_CORREA_M,VC_CORREA_F,VC_LARREA_M,VC_LARREA_F
0,2006,1,5,48,200,0.0,0.0,900.0,961.0,GUTIERREZ GILMAR,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2006,1,5,1,200,0.0,0.0,900.0,961.0,DAMERVAL JAIME,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2006,1,5,4,200,0.0,0.0,900.0,961.0,VITERI CYNTHIA,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2006,1,5,5,200,0.0,0.0,900.0,961.0,NOBOA ALVARO,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2006,1,5,6,200,0.0,0.0,900.0,961.0,ROSERO FERNANDO,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3388,2006,1,995,10,20,0.0,0.0,99.0,99.0,MACAS LUIS,...,64.0,48.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3389,2006,1,995,16,20,0.0,0.0,99.0,99.0,TORRES LENIN,...,0.0,0.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
3390,2006,1,995,55,20,0.0,0.0,99.0,99.0,PROAÑO MAYA MARCO,...,0.0,0.0,0.0,0.0,29.0,40.0,0.0,0.0,0.0,0.0
3391,2006,1,995,72,20,0.0,0.0,99.0,99.0,CORREA DELGADO RAFAEL,...,0.0,0.0,0.0,0.0,0.0,0.0,705.0,525.0,0.0,0.0
3392,2006,1,995,62,20,0.0,0.0,99.0,99.0,LARREA CABRERA MARCELO,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,4.0

In [57]:

columnas_votos = [f'VC_{candidato.split()[0]}_M' for candidato in candidatos_dict.keys()] + [f'VC_{candidato.split()[0]}_F' for candidato in candidatos_dict.keys()]
columnas_votos

['VC_GUTIERREZ_M',
 'VC_DAMERVAL_M',
 'VC_VITERI_M',
 'VC_NOBOA_M',
 'VC_ROSERO_M',
 'VC_ROLDOS_M',
 'VC_SAGNAY_M',
 'VC_VILLACIS_M',
 'VC_MACAS_M',
 'VC_TORRES_M',
 'VC_PROAÑO_M',
 'VC_CORREA_M',
 'VC_LARREA_M',
 'VC_GUTIERREZ_F',
 'VC_DAMERVAL_F',
 'VC_VITERI_F',
 'VC_NOBOA_F',
 'VC_ROSERO_F',
 'VC_ROLDOS_F',
 'VC_SAGNAY_F',
 'VC_VILLACIS_F',
 'VC_MACAS_F',
 'VC_TORRES_F',
 'VC_PROAÑO_F',
 'VC_CORREA_F',
 'VC_LARREA_F']

In [58]:
#Agregado por CANTON
cne2006agFV1CANTON= cne2006agFV1.groupby(['CANTON_CODIGO']).agg({
    'VOTOS_NULOS_M':'mean',
    'VOTOS_NULOS_F':'mean',
    'VOTOS_BLANCOS_M': 'mean',
    'VOTOS_BLANCOS_F': 'mean',
**{columna: 'sum' for columna in columnas_votos}

}).reset_index()

cne2006agFV1CANTON

,CANTON_CODIGO,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,VC_GUTIERREZ_M,VC_DAMERVAL_M,VC_VITERI_M,VC_NOBOA_M,VC_ROSERO_M,...,VC_NOBOA_F,VC_ROSERO_F,VC_ROLDOS_F,VC_SAGNAY_F,VC_VILLACIS_F,VC_MACAS_F,VC_TORRES_F,VC_PROAÑO_F,VC_CORREA_F,VC_LARREA_F
0,5,0.0,0.0,900.0,961.0,683.0,45.0,948.0,7168.0,177.0,...,7785.0,130.0,3204.0,38.0,134.0,212.0,51.0,890.0,4237.0,59.0
1,10,0.0,0.0,486.0,473.0,474.0,21.0,193.0,1950.0,134.0,...,1884.0,104.0,1159.0,22.0,82.0,362.0,55.0,211.0,2157.0,28.0
2,11,0.0,0.0,1.0,1.0,3.0,1.0,7.0,5.0,2.0,...,24.0,2.0,34.0,0.0,1.0,9.0,0.0,1.0,21.0,3.0
3,15,0.0,0.0,200.0,305.0,260.0,11.0,134.0,997.0,38.0,...,948.0,49.0,489.0,10.0,32.0,140.0,6.0,196.0,1009.0,15.0
4,20,0.0,0.0,241.0,276.0,242.0,6.0,110.0,607.0,155.0,...,567.0,120.0,441.0,9.0,48.0,29.0,10.0,184.0,667.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,981,0.0,0.0,36.0,54.0,262.0,2.0,16.0,48.0,3.0,...,42.0,1.0,24.0,0.0,2.0,55.0,1.0,6.0,63.0,0.0
257,985,0.0,0.0,131.0,168.0,891.0,10.0,232.0,389.0,44.0,...,342.0,27.0,123.0,2.0,33.0,6.0,4.0,21.0,186.0,1.0
258,986,0.0,0.0,348.0,204.0,428.0,5.0,268.0,792.0,51.0,...,608.0,49.0,85.0,3.0,37.0,4.0,3.0,6.0,103.0,3.0
259,990,0.0,0.0,26.0,47.0,119.0,1.0,51.0,120.0,3.0,...,112.0,3.0,60.0,0.0,5.0,13.0,1.0,10.0,222.0,2.0
260,995,0.0,0.0,99.0,99.0,96.0,5.0,53.0,635.0,21.0,...,636.0,17.0,354.0,2.0,12.0,48.0,4.0,40.0,525.0,4.0

In [59]:
cne2006agFV1CANTON['CANTON_CODIGO'] = cne2006agFV1CANTON['CANTON_CODIGO'].astype(int)
cne2006RPA['CANTON_CODIGO'] = cne2006RPA['CANTON_CODIGO'].astype(int)

In [60]:
#Match llave primaria para unir a los electores por canton

cne2006agFV1CANTON['ELECTORES_M'] = cne2006agFV1CANTON['CANTON_CODIGO'].map(cne2006RPA.set_index('CANTON_CODIGO')['ELECTORES_M'])
cne2006agFV1CANTON['ELECTORAS_F'] = cne2006agFV1CANTON['CANTON_CODIGO'].map(cne2006RPA.set_index('CANTON_CODIGO')['ELECTORAS_F'])

cne2006agFV1CANTON

,CANTON_CODIGO,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,VC_GUTIERREZ_M,VC_DAMERVAL_M,VC_VITERI_M,VC_NOBOA_M,VC_ROSERO_M,...,VC_ROLDOS_F,VC_SAGNAY_F,VC_VILLACIS_F,VC_MACAS_F,VC_TORRES_F,VC_PROAÑO_F,VC_CORREA_F,VC_LARREA_F,ELECTORES_M,ELECTORAS_F
0,5,0.0,0.0,900.0,961.0,683.0,45.0,948.0,7168.0,177.0,...,3204.0,38.0,134.0,212.0,51.0,890.0,4237.0,59.0,28887.0,29423.0
1,10,0.0,0.0,486.0,473.0,474.0,21.0,193.0,1950.0,134.0,...,1159.0,22.0,82.0,362.0,55.0,211.0,2157.0,28.0,11161.0,11774.0
2,11,0.0,0.0,1.0,1.0,3.0,1.0,7.0,5.0,2.0,...,34.0,0.0,1.0,9.0,0.0,1.0,21.0,3.0,184.0,343.0
3,15,0.0,0.0,200.0,305.0,260.0,11.0,134.0,997.0,38.0,...,489.0,10.0,32.0,140.0,6.0,196.0,1009.0,15.0,5424.0,5741.0
4,20,0.0,0.0,241.0,276.0,242.0,6.0,110.0,607.0,155.0,...,441.0,9.0,48.0,29.0,10.0,184.0,667.0,8.0,4855.0,4797.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,981,0.0,0.0,36.0,54.0,262.0,2.0,16.0,48.0,3.0,...,24.0,0.0,2.0,55.0,1.0,6.0,63.0,0.0,866.0,784.0
257,985,0.0,0.0,131.0,168.0,891.0,10.0,232.0,389.0,44.0,...,123.0,2.0,33.0,6.0,4.0,21.0,186.0,1.0,3509.0,3227.0
258,986,0.0,0.0,348.0,204.0,428.0,5.0,268.0,792.0,51.0,...,85.0,3.0,37.0,4.0,3.0,6.0,103.0,3.0,2875.0,2571.0
259,990,0.0,0.0,26.0,47.0,119.0,1.0,51.0,120.0,3.0,...,60.0,0.0,5.0,13.0,1.0,10.0,222.0,2.0,1224.0,1311.0
260,995,0.0,0.0,99.0,99.0,96.0,5.0,53.0,635.0,21.0,...,354.0,2.0,12.0,48.0,4.0,40.0,525.0,4.0,2803.0,2798.0

In [61]:
#Creación de votos válidos
#Calcula la columna "VOTOS VALIDOS"
cne2006agFV1CANTON["VOTOS VALIDOS"] = cne2006agFV1CANTON[columnas_votos].sum(axis=1)
cne2006agFV1CANTON

,CANTON_CODIGO,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,VC_GUTIERREZ_M,VC_DAMERVAL_M,VC_VITERI_M,VC_NOBOA_M,VC_ROSERO_M,...,VC_SAGNAY_F,VC_VILLACIS_F,VC_MACAS_F,VC_TORRES_F,VC_PROAÑO_F,VC_CORREA_F,VC_LARREA_F,ELECTORES_M,ELECTORAS_F,VOTOS VALIDOS
0,5,0.0,0.0,900.0,961.0,683.0,45.0,948.0,7168.0,177.0,...,38.0,134.0,212.0,51.0,890.0,4237.0,59.0,28887.0,29423.0,37574.0
1,10,0.0,0.0,486.0,473.0,474.0,21.0,193.0,1950.0,134.0,...,22.0,82.0,362.0,55.0,211.0,2157.0,28.0,11161.0,11774.0,14083.0
2,11,0.0,0.0,1.0,1.0,3.0,1.0,7.0,5.0,2.0,...,0.0,1.0,9.0,0.0,1.0,21.0,3.0,184.0,343.0,197.0
3,15,0.0,0.0,200.0,305.0,260.0,11.0,134.0,997.0,38.0,...,10.0,32.0,140.0,6.0,196.0,1009.0,15.0,5424.0,5741.0,6887.0
4,20,0.0,0.0,241.0,276.0,242.0,6.0,110.0,607.0,155.0,...,9.0,48.0,29.0,10.0,184.0,667.0,8.0,4855.0,4797.0,5099.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,981,0.0,0.0,36.0,54.0,262.0,2.0,16.0,48.0,3.0,...,0.0,2.0,55.0,1.0,6.0,63.0,0.0,866.0,784.0,1020.0
257,985,0.0,0.0,131.0,168.0,891.0,10.0,232.0,389.0,44.0,...,2.0,33.0,6.0,4.0,21.0,186.0,1.0,3509.0,3227.0,3995.0
258,986,0.0,0.0,348.0,204.0,428.0,5.0,268.0,792.0,51.0,...,3.0,37.0,4.0,3.0,6.0,103.0,3.0,2875.0,2571.0,3641.0
259,990,0.0,0.0,26.0,47.0,119.0,1.0,51.0,120.0,3.0,...,0.0,5.0,13.0,1.0,10.0,222.0,2.0,1224.0,1311.0,1314.0
260,995,0.0,0.0,99.0,99.0,96.0,5.0,53.0,635.0,21.0,...,2.0,12.0,48.0,4.0,40.0,525.0,4.0,2803.0,2798.0,3856.0

In [62]:
#Define la lista de columnas de votos inválidos
columnas_votos_invalidos = ["VOTOS_NULOS_M", "VOTOS_NULOS_F", "VOTOS_BLANCOS_M", "VOTOS_BLANCOS_F"]

# Calcula la columna "VOTOS_INVALIDOS"
cne2006agFV1CANTON["VOTOS_INVALIDOS"] = cne2006agFV1CANTON[columnas_votos_invalidos].sum(axis=1)

### Match de Cantones

In [63]:
#Match de CANTONs

cne2006agFV1CANTON['CANTON_CODIGO'] = cne2006agFV1CANTON['CANTON_CODIGO'].astype(int)
cne2006RPA['CANTON_CODIGO'] = cne2006RPA['CANTON_CODIGO'].astype(int)

In [64]:
cantones_2006= pd.read_spss("../raw/diccionarios/cantones 2006.sav")

In [65]:
cantones_2006

     PROVINCIA_CODIGO PROVINCIA_NOMBRE  CANTON_CODIGO CANTON_NOMBRE
0                 1.0            AZUAY          260.0        CUENCA
1                 1.0            AZUAY          265.0      GUALACEO
2                 1.0            AZUAY          270.0         GIRON
3                 1.0            AZUAY          275.0         PAUTE
4                 1.0            AZUAY          280.0        SIGSIG
..                ...              ...            ...           ...
256              25.0    VOTO EXTERIOR          391.0       URUGUAY
257              25.0    VOTO EXTERIOR          401.0     VENEZUELA
258              25.0    VOTO EXTERIOR          411.0     INDONESIA
259              25.0    VOTO EXTERIOR          421.0       MALASIA
260              25.0    VOTO EXTERIOR          431.0       POLONIA

[261 rows x 4 columns]

In [66]:
#cne2006agFV1CANTON['PARROQUIA_NOMBRE'] = cne2006agFV1CANTON['CANTON_CODIGO'].map(cantones_2006.set_index('CANTON_CODIGO')['PARROQUIA_NOMBRE'])
cne2006agFV1CANTON['CANTON_NOMBRE'] = cne2006agFV1CANTON['CANTON_CODIGO'].map(cantones_2006.set_index('CANTON_CODIGO')['CANTON_NOMBRE'])
cne2006agFV1CANTON['PROVINCIA_NOMBRE'] = cne2006agFV1CANTON['CANTON_CODIGO'].map(cantones_2006.set_index('CANTON_CODIGO')['PROVINCIA_NOMBRE'])
cne2006agFV1CANTON

,CANTON_CODIGO,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,VC_GUTIERREZ_M,VC_DAMERVAL_M,VC_VITERI_M,VC_NOBOA_M,VC_ROSERO_M,...,VC_TORRES_F,VC_PROAÑO_F,VC_CORREA_F,VC_LARREA_F,ELECTORES_M,ELECTORAS_F,VOTOS VALIDOS,VOTOS_INVALIDOS,CANTON_NOMBRE,PROVINCIA_NOMBRE
0,5,0.0,0.0,900.0,961.0,683.0,45.0,948.0,7168.0,177.0,...,51.0,890.0,4237.0,59.0,28887.0,29423.0,37574.0,1861.0,TULCAN,CARCHI
1,10,0.0,0.0,486.0,473.0,474.0,21.0,193.0,1950.0,134.0,...,55.0,211.0,2157.0,28.0,11161.0,11774.0,14083.0,959.0,MONTUFAR,CARCHI
2,11,0.0,0.0,1.0,1.0,3.0,1.0,7.0,5.0,2.0,...,0.0,1.0,21.0,3.0,184.0,343.0,197.0,2.0,ALEMANIA,VOTO EXTERIOR
3,15,0.0,0.0,200.0,305.0,260.0,11.0,134.0,997.0,38.0,...,6.0,196.0,1009.0,15.0,5424.0,5741.0,6887.0,505.0,ESPEJO,CARCHI
4,20,0.0,0.0,241.0,276.0,242.0,6.0,110.0,607.0,155.0,...,10.0,184.0,667.0,8.0,4855.0,4797.0,5099.0,517.0,MIRA,CARCHI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,981,0.0,0.0,36.0,54.0,262.0,2.0,16.0,48.0,3.0,...,1.0,6.0,63.0,0.0,866.0,784.0,1020.0,90.0,PAQUISHA,ZAMORA CHINCHIPE
257,985,0.0,0.0,131.0,168.0,891.0,10.0,232.0,389.0,44.0,...,4.0,21.0,186.0,1.0,3509.0,3227.0,3995.0,299.0,GRAL. A. ELIZALDE,GUAYAS
258,986,0.0,0.0,348.0,204.0,428.0,5.0,268.0,792.0,51.0,...,3.0,6.0,103.0,3.0,2875.0,2571.0,3641.0,552.0,ISIDRO AYORA,GUAYAS
259,990,0.0,0.0,26.0,47.0,119.0,1.0,51.0,120.0,3.0,...,1.0,10.0,222.0,2.0,1224.0,1311.0,1314.0,73.0,GUACHAPALA,AZUAY
260,995,0.0,0.0,99.0,99.0,96.0,5.0,53.0,635.0,21.0,...,4.0,40.0,525.0,4.0,2803.0,2798.0,3856.0,198.0,SAN PEDRO DE HUACA,CARCHI

In [67]:
# Agregar la columna "AÑO" con valor 2004 al principio del dataframe
cne2006agFV1CANTON.insert(0, "AÑO", 2006)

# Agregar la columna "VUELTA" con valor 2 al principio del dataframe
cne2006agFV1CANTON.insert(1, "VUELTA", 1)

cne2006agFV1CANTON

,AÑO,VUELTA,CANTON_CODIGO,VOTOS_NULOS_M,VOTOS_NULOS_F,VOTOS_BLANCOS_M,VOTOS_BLANCOS_F,VC_GUTIERREZ_M,VC_DAMERVAL_M,VC_VITERI_M,...,VC_TORRES_F,VC_PROAÑO_F,VC_CORREA_F,VC_LARREA_F,ELECTORES_M,ELECTORAS_F,VOTOS VALIDOS,VOTOS_INVALIDOS,CANTON_NOMBRE,PROVINCIA_NOMBRE
0,2006,1,5,0.0,0.0,900.0,961.0,683.0,45.0,948.0,...,51.0,890.0,4237.0,59.0,28887.0,29423.0,37574.0,1861.0,TULCAN,CARCHI
1,2006,1,10,0.0,0.0,486.0,473.0,474.0,21.0,193.0,...,55.0,211.0,2157.0,28.0,11161.0,11774.0,14083.0,959.0,MONTUFAR,CARCHI
2,2006,1,11,0.0,0.0,1.0,1.0,3.0,1.0,7.0,...,0.0,1.0,21.0,3.0,184.0,343.0,197.0,2.0,ALEMANIA,VOTO EXTERIOR
3,2006,1,15,0.0,0.0,200.0,305.0,260.0,11.0,134.0,...,6.0,196.0,1009.0,15.0,5424.0,5741.0,6887.0,505.0,ESPEJO,CARCHI
4,2006,1,20,0.0,0.0,241.0,276.0,242.0,6.0,110.0,...,10.0,184.0,667.0,8.0,4855.0,4797.0,5099.0,517.0,MIRA,CARCHI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,2006,1,981,0.0,0.0,36.0,54.0,262.0,2.0,16.0,...,1.0,6.0,63.0,0.0,866.0,784.0,1020.0,90.0,PAQUISHA,ZAMORA CHINCHIPE
257,2006,1,985,0.0,0.0,131.0,168.0,891.0,10.0,232.0,...,4.0,21.0,186.0,1.0,3509.0,3227.0,3995.0,299.0,GRAL. A. ELIZALDE,GUAYAS
258,2006,1,986,0.0,0.0,348.0,204.0,428.0,5.0,268.0,...,3.0,6.0,103.0,3.0,2875.0,2571.0,3641.0,552.0,ISIDRO AYORA,GUAYAS
259,2006,1,990,0.0,0.0,26.0,47.0,119.0,1.0,51.0,...,1.0,10.0,222.0,2.0,1224.0,1311.0,1314.0,73.0,GUACHAPALA,AZUAY
260,2006,1,995,0.0,0.0,99.0,99.0,96.0,5.0,53.0,...,4.0,40.0,525.0,4.0,2803.0,2798.0,3856.0,198.0,SAN PEDRO DE HUACA,CARCHI

In [68]:
cne2006agFV1CANTON.to_csv('../bases_limpias/cne2006agFV1CANTON.csv')

# To Do
- [x] Cargar y Preparar Datos
- [x] Mapeo de Códigos de Provincia
- [ ] Mapeo de Códigos de Cantón
- [ ] Mapeo de Códigos de Parroquia
- [x] Revision de electores, sufragantes, votos inválidos, votos válidos
- [x] Pasar de codigo de Candidato a codigo de organización política
- [masomenos] Crear funcion para crear nuevas columnas con el apellido del candidato y los votos por sexo
- [ ] Codificar el nulo y el blanco como un candidato más

In [69]:
#creacion funciones para automatizar
def crear_diccionario_candidatos(df):
    candidatos_dict = dict(zip(df['CANDIDATO_NOMBRE'], df['OP_CODIGO']))
    return candidatos_dict
    
    
    
def agregar_columnas_votos(df, candidatos_dict):
    for candidato in candidatos_dict.keys():
        columna_m = f'VC_{candidato.split()[0]}_M'
        columna_f = f'VC_{candidato.split()[0]}_F'
        df[columna_m]= df.loc[df['CANDIDATO_NOMBRE'] == candidato, 'VOTOS_CANDIDATO_M']
        df[columna_f]= df.loc[df['CANDIDATO_NOMBRE'] == candidato, 'VOTOS_CANDIDATO_F']
        df[columna_f]= df[columna_f].fillna(0)
        df[columna_m]= df[columna_m].fillna(0)
    return df